module Anthropic
  module Models
    module Beta
      module Organization
        type beta_analytics_connector_chat_cowork_unified_chat_metrics =
          { distinct_conversation_connector_used_count: Integer? }

        class BetaAnalyticsConnectorChatCoworkUnifiedChatMetrics < Anthropic::Internal::Type::BaseModel
          attr_accessor distinct_conversation_connector_used_count: Integer?

          def initialize: (
            distinct_conversation_connector_used_count: Integer?
          ) -> void

          def to_hash: -> {
            distinct_conversation_connector_used_count: Integer?
          }
        end
      end
    end
  end
end
