module Anthropic
  module Models
    module Beta
      module Organization
        type beta_analytics_skill_activity =
          {
            chat_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillChatMetrics,
            claude_code_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillClaudeCodeMetrics,
            cowork_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillCoworkMetrics,
            distinct_user_count: Integer,
            office_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillOfficeMetrics,
            skill_name: String,
            attributed_list_price: String?,
            chat_cowork_unified_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics?,
            currency: String?,
            enable_count: Integer?,
            estimated_overage_spend: String?,
            invocation_count: Integer?,
            product: String?,
            rbac_group_id: String?,
            rbac_group_name: String?,
            share_status: Anthropic::Models::Beta::Organization::BetaAnalyticsSkillActivity::share_status?,
            skill_display_name: String?,
            user_id: String?
          }

        class BetaAnalyticsSkillActivity < Anthropic::Internal::Type::BaseModel
          attr_accessor chat_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillChatMetrics

          attr_accessor claude_code_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillClaudeCodeMetrics

          attr_accessor cowork_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillCoworkMetrics

          attr_accessor distinct_user_count: Integer

          attr_accessor office_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillOfficeMetrics

          attr_accessor skill_name: String

          attr_accessor attributed_list_price: String?

          attr_accessor chat_cowork_unified_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics?

          attr_accessor currency: String?

          attr_accessor enable_count: Integer?

          attr_accessor estimated_overage_spend: String?

          attr_accessor invocation_count: Integer?

          attr_accessor product: String?

          attr_accessor rbac_group_id: String?

          attr_accessor rbac_group_name: String?

          attr_accessor share_status: Anthropic::Models::Beta::Organization::BetaAnalyticsSkillActivity::share_status?

          attr_accessor skill_display_name: String?

          attr_accessor user_id: String?

          def initialize: (
            chat_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillChatMetrics,
            claude_code_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillClaudeCodeMetrics,
            cowork_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillCoworkMetrics,
            distinct_user_count: Integer,
            office_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillOfficeMetrics,
            skill_name: String,
            ?attributed_list_price: String?,
            ?chat_cowork_unified_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics?,
            ?currency: String?,
            ?enable_count: Integer?,
            ?estimated_overage_spend: String?,
            ?invocation_count: Integer?,
            ?product: String?,
            ?rbac_group_id: String?,
            ?rbac_group_name: String?,
            ?share_status: Anthropic::Models::Beta::Organization::BetaAnalyticsSkillActivity::share_status?,
            ?skill_display_name: String?,
            ?user_id: String?
          ) -> void

          def to_hash: -> {
            chat_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillChatMetrics,
            claude_code_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillClaudeCodeMetrics,
            cowork_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillCoworkMetrics,
            distinct_user_count: Integer,
            office_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillOfficeMetrics,
            skill_name: String,
            attributed_list_price: String?,
            chat_cowork_unified_metrics: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics?,
            currency: String?,
            enable_count: Integer?,
            estimated_overage_spend: String?,
            invocation_count: Integer?,
            product: String?,
            rbac_group_id: String?,
            rbac_group_name: String?,
            share_status: Anthropic::Models::Beta::Organization::BetaAnalyticsSkillActivity::share_status?,
            skill_display_name: String?,
            user_id: String?
          }

          type chat_cowork_unified_metrics =
            {
              chat: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Chat,
              sessions: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Sessions
            }

          class ChatCoworkUnifiedMetrics < Anthropic::Internal::Type::BaseModel
            attr_accessor chat: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Chat

            attr_accessor sessions: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Sessions

            def initialize: (
              chat: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Chat,
              sessions: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Sessions
            ) -> void

            def to_hash: -> {
              chat: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Chat,
              sessions: Anthropic::Beta::Organization::BetaAnalyticsSkillActivity::ChatCoworkUnifiedMetrics::Sessions
            }

            type chat = { distinct_conversation_skill_used_count: Integer? }

            class Chat < Anthropic::Internal::Type::BaseModel
              attr_accessor distinct_conversation_skill_used_count: Integer?

              def initialize: (
                distinct_conversation_skill_used_count: Integer?
              ) -> void

              def to_hash: -> {
                distinct_conversation_skill_used_count: Integer?
              }
            end

            type sessions = { distinct_session_skill_used_count: Integer? }

            class Sessions < Anthropic::Internal::Type::BaseModel
              attr_accessor distinct_session_skill_used_count: Integer?

              def initialize: (
                distinct_session_skill_used_count: Integer?
              ) -> void

              def to_hash: -> { distinct_session_skill_used_count: Integer? }
            end
          end

          type share_status = :organization | :private | :public

          module ShareStatus
            extend Anthropic::Internal::Type::Enum

            ORGANIZATION: :organization
            PRIVATE: :private
            PUBLIC: :public

            def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::BetaAnalyticsSkillActivity::share_status]
          end
        end
      end
    end
  end
end
