module Anthropic
  module Models
    module Beta
      module Organization
        type beta_spend_limit_rbac_group_scope =
          { rbac_group_id: String, type: :rbac_group }

        class BetaSpendLimitRBACGroupScope < Anthropic::Internal::Type::BaseModel
          attr_accessor rbac_group_id: String

          attr_accessor type: :rbac_group

          def initialize: (rbac_group_id: String, ?type: :rbac_group) -> void

          def to_hash: -> { rbac_group_id: String, type: :rbac_group }
        end
      end
    end
  end
end
