module Anthropic
  class Unknown = Anthropic::Internal::Type::Unknown

  class BooleanModel = Anthropic::Internal::Type::BooleanModel

  module Enum = Anthropic::Internal::Type::Enum

  module Union = Anthropic::Internal::Type::Union

  class ArrayOf = Anthropic::Internal::Type::ArrayOf

  class HashOf = Anthropic::Internal::Type::HashOf

  class BaseModel = Anthropic::Internal::Type::BaseModel

  type request_parameters = Anthropic::Internal::Type::request_parameters

  module RequestParameters = Anthropic::Internal::Type::RequestParameters
end
