module Anthropic
  class BaseStream[Elem]
    def initialize: (
      model: Class | Anthropic::Converter,
      url: URI::Generic,
      status: Integer,
      response: top,
      messages: Enumerable[Anthropic::Util::sse_message]
    ) -> void

    private def iterator: -> Enumerable[Elem]

    def close: -> void

    def for_each: { (Elem arg0) -> void } -> void

    def to_enum: -> Enumerable[Elem]

    alias enum_for to_enum
  end
end
