module Anthropic
  class Page[Elem]
    include Anthropic::BasePage[Elem]

    attr_accessor data: ::Array[Elem]

    attr_accessor has_more: bool

    attr_accessor first_id: String?

    attr_accessor last_id: String?
  end
end
