module Anthropic
  module Models
    module Messages
      type batch_delete_params = {  } & Anthropic::request_parameters

      class BatchDeleteParams < Anthropic::BaseModel
        extend Anthropic::Type::RequestParameters::Converter
        include Anthropic::RequestParameters

        def initialize: (?request_options: Anthropic::request_opts) -> void

        def to_hash: -> Anthropic::Models::Messages::batch_delete_params
      end
    end
  end
end
