# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaToolUseBlock < Anthropic::Internal::Type::BaseModel
        # @!attribute id
        #
        #   @return [String]
        required :id, String

        # @!attribute input
        #
        #   @return [Hash{Symbol=>Object}]
        required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

        # @!attribute name
        #
        #   @return [String]
        required :name, String

        # @!attribute type
        #
        #   @return [Symbol, :tool_use]
        required :type, const: :tool_use

        # @!attribute caller_
        #   Tool invocation directly from the model.
        #
        #   @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, nil]
        optional :caller_, union: -> { Anthropic::Beta::BetaToolUseBlock::Caller }, api_name: :caller

        # @!method initialize(id:, input:, name:, caller_: nil, type: :tool_use)
        #   @param id [String]
        #
        #   @param input [Hash{Symbol=>Object}]
        #
        #   @param name [String]
        #
        #   @param caller_ [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller] Tool invocation directly from the model.
        #
        #   @param type [Symbol, :tool_use]

        # Tool invocation directly from the model.
        #
        # @see Anthropic::Models::Beta::BetaToolUseBlock#caller_
        module Caller
          extend Anthropic::Internal::Type::Union

          discriminator :type

          # Tool invocation directly from the model.
          variant :direct, -> { Anthropic::Beta::BetaDirectCaller }

          # Tool invocation generated by a server-side tool.
          variant :code_execution_20250825, -> { Anthropic::Beta::BetaServerToolCaller }

          # @!method self.variants
          #   @return [Array(Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller)]
        end
      end
    end

    BetaToolUseBlock = Beta::BetaToolUseBlock
  end
end
