# frozen_string_literal: true

module Anthropic
  module Models
    module Beta
      class BetaServerToolUseBlock < Anthropic::Internal::Type::BaseModel
        # @!attribute id
        #
        #   @return [String]
        required :id, String

        # @!attribute input
        #
        #   @return [Hash{Symbol=>Object}]
        required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

        # @!attribute name
        #
        #   @return [Symbol, Anthropic::Models::Beta::BetaServerToolUseBlock::Name]
        required :name, enum: -> { Anthropic::Beta::BetaServerToolUseBlock::Name }

        # @!attribute type
        #
        #   @return [Symbol, :server_tool_use]
        required :type, const: :server_tool_use

        # @!attribute caller_
        #   Tool invocation directly from the model.
        #
        #   @return [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller, nil]
        optional :caller_, union: -> { Anthropic::Beta::BetaServerToolUseBlock::Caller }, api_name: :caller

        # @!method initialize(id:, input:, name:, caller_: nil, type: :server_tool_use)
        #   @param id [String]
        #
        #   @param input [Hash{Symbol=>Object}]
        #
        #   @param name [Symbol, Anthropic::Models::Beta::BetaServerToolUseBlock::Name]
        #
        #   @param caller_ [Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller] Tool invocation directly from the model.
        #
        #   @param type [Symbol, :server_tool_use]

        # @see Anthropic::Models::Beta::BetaServerToolUseBlock#name
        module Name
          extend Anthropic::Internal::Type::Enum

          WEB_SEARCH = :web_search
          WEB_FETCH = :web_fetch
          CODE_EXECUTION = :code_execution
          BASH_CODE_EXECUTION = :bash_code_execution
          TEXT_EDITOR_CODE_EXECUTION = :text_editor_code_execution
          TOOL_SEARCH_TOOL_REGEX = :tool_search_tool_regex
          TOOL_SEARCH_TOOL_BM25 = :tool_search_tool_bm25

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # Tool invocation directly from the model.
        #
        # @see Anthropic::Models::Beta::BetaServerToolUseBlock#caller_
        module Caller
          extend Anthropic::Internal::Type::Union

          discriminator :type

          # Tool invocation directly from the model.
          variant :direct, -> { Anthropic::Beta::BetaDirectCaller }

          # Tool invocation generated by a server-side tool.
          variant :code_execution_20250825, -> { Anthropic::Beta::BetaServerToolCaller }

          # @!method self.variants
          #   @return [Array(Anthropic::Models::Beta::BetaDirectCaller, Anthropic::Models::Beta::BetaServerToolCaller)]
        end
      end
    end

    BetaServerToolUseBlock = Beta::BetaServerToolUseBlock
  end
end
