# frozen_string_literal: true

module Anthropic
  module Models
    class ServerToolUseBlock < Anthropic::Internal::Type::BaseModel
      # @!attribute id
      #
      #   @return [String]
      required :id, String

      # @!attribute caller_
      #   Tool invocation directly from the model.
      #
      #   @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolUseBlock::Caller::CodeExecution20260120]
      required :caller_, union: -> { Anthropic::ServerToolUseBlock::Caller }, api_name: :caller

      # @!attribute input
      #
      #   @return [Hash{Symbol=>Object}]
      required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

      # @!attribute name
      #
      #   @return [Symbol, Anthropic::Models::ServerToolUseBlock::Name]
      required :name, enum: -> { Anthropic::ServerToolUseBlock::Name }

      # @!attribute type
      #
      #   @return [Symbol, :server_tool_use]
      required :type, const: :server_tool_use

      # @!method initialize(id:, caller_:, input:, name:, type: :server_tool_use)
      #   @param id [String]
      #
      #   @param caller_ [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolUseBlock::Caller::CodeExecution20260120] Tool invocation directly from the model.
      #
      #   @param input [Hash{Symbol=>Object}]
      #
      #   @param name [Symbol, Anthropic::Models::ServerToolUseBlock::Name]
      #
      #   @param type [Symbol, :server_tool_use]

      # Tool invocation directly from the model.
      #
      # @see Anthropic::Models::ServerToolUseBlock#caller_
      module Caller
        extend Anthropic::Internal::Type::Union

        discriminator :type

        # Tool invocation directly from the model.
        variant :direct, -> { Anthropic::DirectCaller }

        # Tool invocation generated by a server-side tool.
        variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

        variant :code_execution_20260120, -> { Anthropic::ServerToolUseBlock::Caller::CodeExecution20260120 }

        class CodeExecution20260120 < Anthropic::Internal::Type::BaseModel
          # @!attribute tool_id
          #
          #   @return [String]
          required :tool_id, String

          # @!attribute type
          #
          #   @return [Symbol, :code_execution_20260120]
          required :type, const: :code_execution_20260120

          # @!method initialize(tool_id:, type: :code_execution_20260120)
          #   @param tool_id [String]
          #   @param type [Symbol, :code_execution_20260120]
        end

        # @!method self.variants
        #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolUseBlock::Caller::CodeExecution20260120)]
      end

      # @see Anthropic::Models::ServerToolUseBlock#name
      module Name
        extend Anthropic::Internal::Type::Enum

        WEB_SEARCH = :web_search
        WEB_FETCH = :web_fetch
        CODE_EXECUTION = :code_execution
        BASH_CODE_EXECUTION = :bash_code_execution
        TEXT_EDITOR_CODE_EXECUTION = :text_editor_code_execution
        TOOL_SEARCH_TOOL_REGEX = :tool_search_tool_regex
        TOOL_SEARCH_TOOL_BM25 = :tool_search_tool_bm25

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
