# frozen_string_literal: true

module Anthropic
  module Models
    class ToolUseBlock < Anthropic::Internal::Type::BaseModel
      # @!attribute id
      #
      #   @return [String]
      required :id, String

      # @!attribute caller_
      #   Tool invocation directly from the model.
      #
      #   @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      required :caller_, union: -> { Anthropic::ToolUseBlock::Caller }, api_name: :caller

      # @!attribute input
      #
      #   @return [Hash{Symbol=>Object}]
      required :input, Anthropic::Internal::Type::HashOf[Anthropic::Internal::Type::Unknown]

      # @!attribute name
      #
      #   @return [String]
      required :name, String

      # @!attribute type
      #
      #   @return [Symbol, :tool_use]
      required :type, const: :tool_use

      # @!method initialize(id:, caller_:, input:, name:, type: :tool_use)
      #   @param id [String]
      #
      #   @param caller_ [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120] Tool invocation directly from the model.
      #
      #   @param input [Hash{Symbol=>Object}]
      #
      #   @param name [String]
      #
      #   @param type [Symbol, :tool_use]

      # Tool invocation directly from the model.
      #
      # @see Anthropic::Models::ToolUseBlock#caller_
      module Caller
        extend Anthropic::Internal::Type::Union

        discriminator :type

        # Tool invocation directly from the model.
        variant :direct, -> { Anthropic::DirectCaller }

        # Tool invocation generated by a server-side tool.
        variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

        variant :code_execution_20260120, -> { Anthropic::ServerToolCaller20260120 }

        # @!method self.variants
        #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120)]
      end
    end
  end
end
