# frozen_string_literal: true

module Anthropic
  module Models
    # Which party invoked the tool call: the model directly, or a server tool on its
    # behalf.
    module ToolUseCaller
      extend Anthropic::Internal::Type::Union

      discriminator :type

      # Tool invocation directly from the model.
      variant :direct, -> { Anthropic::DirectCaller }

      # Tool invocation generated by a server-side tool.
      variant :code_execution_20250825, -> { Anthropic::ServerToolCaller }

      variant :code_execution_20260120, -> { Anthropic::ServerToolCaller20260120 }

      module Type
        extend Anthropic::Internal::Type::Enum

        DIRECT = :direct
        CODE_EXECUTION_20250825 = :code_execution_20250825
        CODE_EXECUTION_20260120 = :code_execution_20260120

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # @!method self.variants
      #   @return [Array(Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120)]

      # Creates a new instance of the variant class whose `type` matches the given
      # value, passing the remaining arguments to its constructor.
      #
      # @param type [Symbol, Anthropic::Models::ToolUseCaller::Type, String]
      #
      # @param args [Hash{Symbol=>Object}] Attributes for the chosen variant.
      #
      #   @option args [String] :tool_id
      #
      # @raise [ArgumentError]
      # @return [Anthropic::Models::DirectCaller, Anthropic::Models::ServerToolCaller, Anthropic::Models::ServerToolCaller20260120]
      def self.new(type:, **args)
        case type.to_sym
        when :direct
          Anthropic::DirectCaller.new(**args)
        when :code_execution_20250825
          Anthropic::ServerToolCaller.new(**args)
        when :code_execution_20260120
          Anthropic::ServerToolCaller20260120.new(**args)
        else
          raise ArgumentError, "unknown type: #{type}"
        end
      end
    end
  end
end
