module Anthropic
  module Resources
    class Organization
      class ServiceAccounts
        attr_reader workspaces: Anthropic::Resources::Organization::ServiceAccounts::Workspaces

        def create: (
          name: String,
          ?description: String?,
          ?organization_role: Anthropic::Models::Organization::ServiceAccountCreateParams::organization_role,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Organization::ServiceAccount

        def retrieve: (
          String service_account_id,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Organization::ServiceAccount

        def update: (
          String service_account_id,
          ?description: String?,
          ?organization_role: Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role?,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Organization::ServiceAccount

        def list: (
          ?include_archived: bool,
          ?limit: Integer,
          ?page: String?,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Internal::PageCursor[Anthropic::Organization::ServiceAccount]

        def archive: (
          String service_account_id,
          ?request_options: Anthropic::request_opts
        ) -> Anthropic::Organization::ServiceAccount

        def initialize: (client: Anthropic::Client) -> void
      end
    end
  end
end
