module Anthropic
  module Models
    module Beta
      module MemoryStores
        type beta_managed_agents_actor =
          Anthropic::Beta::MemoryStores::BetaManagedAgentsSessionActor
          | Anthropic::Beta::MemoryStores::BetaManagedAgentsAPIActor
          | Anthropic::Beta::MemoryStores::BetaManagedAgentsUserActor

        module BetaManagedAgentsActor
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Beta::MemoryStores::beta_managed_agents_actor]
        end
      end
    end
  end
end
