module Anthropic
  module Resources
    class Beta
      class Messages
        class Batches
          def create:
            (
              Anthropic::Models::Beta::Messages::BatchCreateParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch
            | (
              requests: Array[Anthropic::Models::Beta::Messages::BatchCreateParams::Request],
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch

          def retrieve:
            (
              String message_batch_id,
              ?Anthropic::Models::Beta::Messages::BatchRetrieveParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch
            | (
              String message_batch_id,
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch

          def list:
            (
              ?Anthropic::Models::Beta::Messages::BatchListParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Page[Anthropic::Models::Beta::Messages::BetaMessageBatch]
            | (
              after_id: String,
              before_id: String,
              limit: Integer,
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Page[Anthropic::Models::Beta::Messages::BetaMessageBatch]

          def delete:
            (
              String message_batch_id,
              ?Anthropic::Models::Beta::Messages::BatchDeleteParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Models::Beta::Messages::BetaDeletedMessageBatch
            | (
              String message_batch_id,
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Models::Beta::Messages::BetaDeletedMessageBatch

          def cancel:
            (
              String message_batch_id,
              ?Anthropic::Models::Beta::Messages::BatchCancelParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch
            | (
              String message_batch_id,
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatch

          def results:
            (
              String message_batch_id,
              ?Anthropic::Models::Beta::Messages::BatchResultsParams
              | Hash[Symbol, top] params
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatchIndividualResponse
            | (
              String message_batch_id,
              betas: Array[Anthropic::Models::anthropic_beta],
              request_options: Anthropic::request_opts
            ) -> Anthropic::Models::Beta::Messages::BetaMessageBatchIndividualResponse

          def initialize: (client: Anthropic::Client) -> void
        end
      end
    end
  end
end
