module Anthropic
  module Models
    module Beta
      module Vaults
        type beta_managed_agents_credential_validation_status =
          :valid | :invalid | :unknown

        module BetaManagedAgentsCredentialValidationStatus
          extend Anthropic::Internal::Type::Enum

          VALID: :valid
          INVALID: :invalid
          UNKNOWN: :unknown

          def self?.values: -> ::Array[Anthropic::Models::Beta::Vaults::beta_managed_agents_credential_validation_status]
        end
      end
    end
  end
end
