module Anthropic
  module Models
    type anthropic_beta =
      String | Anthropic::Models::AnthropicBeta::union_member1

    class AnthropicBeta < Anthropic::Union
      type union_member1 =
        :"message-batches-2024-09-24"
        | :"prompt-caching-2024-07-31"
        | :"computer-use-2024-10-22"
        | :"pdfs-2024-09-25"
        | :"token-counting-2024-11-01"

      class UnionMember1 < Anthropic::Enum
        MESSAGE_BATCHES_2024_09_24: :"message-batches-2024-09-24"
        PROMPT_CACHING_2024_07_31: :"prompt-caching-2024-07-31"
        COMPUTER_USE_2024_10_22: :"computer-use-2024-10-22"
        PDFS_2024_09_25: :"pdfs-2024-09-25"
        TOKEN_COUNTING_2024_11_01: :"token-counting-2024-11-01"

        def self.values: -> ::Array[Anthropic::Models::AnthropicBeta::union_member1]
      end

      private def self.variants: -> [[nil, String], [nil, Anthropic::Models::AnthropicBeta::union_member1]]
    end
  end
end
