module Anthropic
  module Models
    type authentication_error = { message: String, type: :authentication_error }

    class AuthenticationError_ < Anthropic::BaseModel
      attr_accessor message: String

      attr_accessor type: :authentication_error

      def initialize:
        (message: String, type: :authentication_error) -> void
        | (
          ?Anthropic::Models::authentication_error | Anthropic::BaseModel data
        ) -> void

      def to_hash: -> Anthropic::Models::authentication_error
    end
  end
end
