module Anthropic
  module Models
    type beta_error =
      Anthropic::Models::BetaInvalidRequestError
      | Anthropic::Models::BetaAuthenticationError
      | Anthropic::Models::BetaBillingError
      | Anthropic::Models::BetaPermissionError
      | Anthropic::Models::BetaNotFoundError
      | Anthropic::Models::BetaRateLimitError
      | Anthropic::Models::BetaGatewayTimeoutError
      | Anthropic::Models::BetaAPIError
      | Anthropic::Models::BetaOverloadedError

    module BetaError
      extend Anthropic::Internal::Type::Union

      def self?.variants: -> [Anthropic::Models::BetaInvalidRequestError, Anthropic::Models::BetaAuthenticationError, Anthropic::Models::BetaBillingError, Anthropic::Models::BetaPermissionError, Anthropic::Models::BetaNotFoundError, Anthropic::Models::BetaRateLimitError, Anthropic::Models::BetaGatewayTimeoutError, Anthropic::Models::BetaAPIError, Anthropic::Models::BetaOverloadedError]
    end
  end
end
