module Anthropic
  module Models
    type beta_api_error = { message: String, type: :api_error }

    class BetaAPIError < Anthropic::BaseModel
      attr_accessor message: String

      attr_accessor type: :api_error

      def initialize:
        (message: String, type: :api_error) -> void
        | (
          ?Anthropic::Models::beta_api_error | Anthropic::BaseModel data
        ) -> void

      def to_hash: -> Anthropic::Models::beta_api_error
    end
  end
end
