module Anthropic
  module Models
    type browser_screenshot_tool_use_block =
      {
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserScreenshotInput,
        name: :screenshot,
        toolset_name: :browser,
        type: :tool_use
      }

    class BrowserScreenshotToolUseBlock < Anthropic::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor caller_: Anthropic::Models::tool_use_caller

      attr_accessor input: Anthropic::BrowserScreenshotInput

      attr_accessor name: :screenshot

      attr_accessor toolset_name: :browser

      attr_accessor type: :tool_use

      def initialize: (
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserScreenshotInput,
        ?name: :screenshot,
        ?toolset_name: :browser,
        ?type: :tool_use
      ) -> void

      def to_hash: -> {
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserScreenshotInput,
        name: :screenshot,
        toolset_name: :browser,
        type: :tool_use
      }
    end
  end
end
