module Anthropic
  module Models
    type browser_form_input_value = String | Float | bool

    module BrowserFormInputValue
      extend Anthropic::Internal::Type::Union

      def self?.variants: -> ::Array[Anthropic::Models::browser_form_input_value]
    end
  end
end
