module Anthropic
  module Models
    type browser_list_tabs_input = {  }

    class BrowserListTabsInput < Anthropic::Internal::Type::BaseModel
      def initialize: -> void

      def to_hash: -> {  }
    end
  end
end
