module Anthropic
  module Models
    type browser_type_input = { text: String, tab_id: String? }

    class BrowserTypeInput < Anthropic::Internal::Type::BaseModel
      attr_accessor text: String

      attr_accessor tab_id: String?

      def initialize: (text: String, ?tab_id: String?) -> void

      def to_hash: -> { text: String, tab_id: String? }
    end
  end
end
