module Anthropic
  module Models
    type browser_hover_input =
      { target: Anthropic::Models::browser_click_target, tab_id: String? }

    class BrowserHoverInput < Anthropic::Internal::Type::BaseModel
      attr_accessor target: Anthropic::Models::browser_click_target

      attr_accessor tab_id: String?

      def initialize: (
        target: Anthropic::Models::browser_click_target,
        ?tab_id: String?
      ) -> void

      def to_hash: -> {
        target: Anthropic::Models::browser_click_target,
        tab_id: String?
      }
    end
  end
end
