module Anthropic
  module Models
    type browser_left_mouse_down_input =
      { target: Anthropic::BrowserCoordinateTarget, tab_id: String? }

    class BrowserLeftMouseDownInput < Anthropic::Internal::Type::BaseModel
      attr_accessor target: Anthropic::BrowserCoordinateTarget

      attr_accessor tab_id: String?

      def initialize: (
        target: Anthropic::BrowserCoordinateTarget,
        ?tab_id: String?
      ) -> void

      def to_hash: -> {
        target: Anthropic::BrowserCoordinateTarget,
        tab_id: String?
      }
    end
  end
end
