module Anthropic
  module Models
    type browser_close_tab_tool_use_block =
      {
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserCloseTabInput,
        name: :close_tab,
        toolset_name: :browser,
        type: :tool_use
      }

    class BrowserCloseTabToolUseBlock < Anthropic::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor caller_: Anthropic::Models::tool_use_caller

      attr_accessor input: Anthropic::BrowserCloseTabInput

      attr_accessor name: :close_tab

      attr_accessor toolset_name: :browser

      attr_accessor type: :tool_use

      def initialize: (
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserCloseTabInput,
        ?name: :close_tab,
        ?toolset_name: :browser,
        ?type: :tool_use
      ) -> void

      def to_hash: -> {
        id: String,
        caller_: Anthropic::Models::tool_use_caller,
        input: Anthropic::BrowserCloseTabInput,
        name: :close_tab,
        toolset_name: :browser,
        type: :tool_use
      }
    end
  end
end
