module Anthropic
  module Models
    type browser_screenshot_input = { tab_id: String? }

    class BrowserScreenshotInput < Anthropic::Internal::Type::BaseModel
      attr_accessor tab_id: String?

      def initialize: (?tab_id: String?) -> void

      def to_hash: -> { tab_id: String? }
    end
  end
end
