module Anthropic
  module Models
    type cache_miss_model_changed =
      { cache_missed_input_tokens: Integer, type: :model_changed }

    class CacheMissModelChanged < Anthropic::Internal::Type::BaseModel
      attr_accessor cache_missed_input_tokens: Integer

      attr_accessor type: :model_changed

      def initialize: (
        cache_missed_input_tokens: Integer,
        ?type: :model_changed
      ) -> void

      def to_hash: -> {
        cache_missed_input_tokens: Integer,
        type: :model_changed
      }
    end
  end
end
