module Anthropic
  module Models
    type cache_control_ephemeral = { type: :ephemeral }

    class CacheControlEphemeral < Anthropic::BaseModel
      attr_accessor type: :ephemeral

      def initialize: (?type: :ephemeral) -> void

      def to_hash: -> Anthropic::Models::cache_control_ephemeral
    end
  end
end
