module Anthropic
  module Models
    type citations_delta =
      {
        citation: Anthropic::Models::CitationsDelta::citation,
        type: :citations_delta
      }

    class CitationsDelta < Anthropic::BaseModel
      attr_accessor citation: Anthropic::Models::CitationsDelta::citation

      attr_accessor type: :citations_delta

      def initialize: (
        citation: Anthropic::Models::CitationsDelta::citation,
        ?type: :citations_delta
      ) -> void

      def to_hash: -> Anthropic::Models::citations_delta

      type citation =
        Anthropic::Models::CitationCharLocation
        | Anthropic::Models::CitationPageLocation
        | Anthropic::Models::CitationContentBlockLocation

      module Citation
        extend Anthropic::Union

        def self.variants: -> [Anthropic::Models::CitationCharLocation, Anthropic::Models::CitationPageLocation, Anthropic::Models::CitationContentBlockLocation]
      end
    end
  end
end
