module Anthropic
  module Models
    type citations_delta =
      { citation: Anthropic::CitationsDelta::citation, type: :citations_delta }

    class CitationsDelta < Anthropic::Internal::Type::BaseModel
      attr_accessor citation: Anthropic::CitationsDelta::citation

      attr_accessor type: :citations_delta

      def initialize: (
        citation: Anthropic::CitationsDelta::citation,
        ?type: :citations_delta
      ) -> void

      type citation =
        Anthropic::CitationCharLocation
        | Anthropic::CitationPageLocation
        | Anthropic::CitationContentBlockLocation
        | Anthropic::CitationsWebSearchResultLocation

      module Citation
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> ::Array[Anthropic::CitationsDelta::citation]
      end
    end
  end
end
