module Anthropic
  module Models
    type citation_char_location_param =
      {
        cited_text: String,
        document_index: Integer,
        document_title: String?,
        end_char_index: Integer,
        start_char_index: Integer,
        type: :char_location
      }

    class CitationCharLocationParam < Anthropic::BaseModel
      attr_accessor cited_text: String

      attr_accessor document_index: Integer

      attr_accessor document_title: String?

      attr_accessor end_char_index: Integer

      attr_accessor start_char_index: Integer

      attr_accessor type: :char_location

      def initialize:
        (
          cited_text: String,
          document_index: Integer,
          document_title: String?,
          end_char_index: Integer,
          start_char_index: Integer,
          type: :char_location
        ) -> void
        | (
          ?Anthropic::Models::citation_char_location_param
          | Anthropic::BaseModel data
        ) -> void

      def to_hash: -> Anthropic::Models::citation_char_location_param
    end
  end
end
