module Anthropic
  module Models
    type computer_screenshot_input = {  }

    class ComputerScreenshotInput < Anthropic::Internal::Type::BaseModel
      def initialize: -> void

      def to_hash: -> {  }
    end
  end
end
