module Anthropic
  module Models
    type computer_type_input = { text: String }

    class ComputerTypeInput < Anthropic::Internal::Type::BaseModel
      attr_accessor text: String

      def initialize: (text: String) -> void

      def to_hash: -> { text: String }
    end
  end
end
