module Anthropic
  module Models
    type content_block_param =
      Anthropic::Models::TextBlockParam
      | Anthropic::Models::ImageBlockParam
      | Anthropic::Models::ToolUseBlockParam
      | Anthropic::Models::ToolResultBlockParam
      | Anthropic::Models::DocumentBlockParam

    class ContentBlockParam < Anthropic::Union
      private def self.variants: -> [[:text, Anthropic::Models::TextBlockParam], [:image, Anthropic::Models::ImageBlockParam], [:tool_use, Anthropic::Models::ToolUseBlockParam], [:tool_result, Anthropic::Models::ToolResultBlockParam], [:document, Anthropic::Models::DocumentBlockParam]]
    end
  end
end
