module Anthropic
  module Models
    type content_block_source =
      { content: Anthropic::ContentBlockSource::content, type: :content }

    class ContentBlockSource < Anthropic::Internal::Type::BaseModel
      attr_accessor content: Anthropic::ContentBlockSource::content

      attr_accessor type: :content

      def initialize: (
        content: Anthropic::ContentBlockSource::content,
        ?type: :content
      ) -> void

      type content =
        String | ::Array[Anthropic::Models::content_block_source_content]

      module Content
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> ::Array[Anthropic::ContentBlockSource::content]

        ContentBlockSourceContentArray: Anthropic::Internal::Type::Converter
      end
    end
  end
end
