module Anthropic
  module Models
    type content_block =
      Anthropic::Models::TextBlock
      | Anthropic::Models::ToolUseBlock
      | Anthropic::Models::ThinkingBlock
      | Anthropic::Models::RedactedThinkingBlock

    module ContentBlock
      extend Anthropic::Union

      def self?.variants: -> [Anthropic::Models::TextBlock, Anthropic::Models::ToolUseBlock, Anthropic::Models::ThinkingBlock, Anthropic::Models::RedactedThinkingBlock]
    end
  end
end
