module Anthropic
  module Models
    type content_block_source_content =
      Anthropic::Models::TextBlockParam | Anthropic::Models::ImageBlockParam

    class ContentBlockSourceContent < Anthropic::Union
      def self.variants: -> [Anthropic::Models::TextBlockParam, Anthropic::Models::ImageBlockParam]
    end
  end
end
