module Anthropic
  module Models
    type content_block_param =
      Anthropic::Models::TextBlockParam
      | Anthropic::Models::ImageBlockParam
      | Anthropic::Models::ToolUseBlockParam
      | Anthropic::Models::ToolResultBlockParam
      | Anthropic::Models::DocumentBlockParam
      | Anthropic::Models::ThinkingBlockParam
      | Anthropic::Models::RedactedThinkingBlockParam

    module ContentBlockParam
      extend Anthropic::Union

      def self?.variants: -> [Anthropic::Models::TextBlockParam, Anthropic::Models::ImageBlockParam, Anthropic::Models::ToolUseBlockParam, Anthropic::Models::ToolResultBlockParam, Anthropic::Models::DocumentBlockParam, Anthropic::Models::ThinkingBlockParam, Anthropic::Models::RedactedThinkingBlockParam]
    end
  end
end
