module Anthropic
  module Models
    type invalid_request_error =
      { message: String, type: :invalid_request_error }

    class InvalidRequestError < Anthropic::BaseModel
      attr_accessor message: String

      attr_accessor type: :invalid_request_error

      def initialize:
        (message: String, type: :invalid_request_error) -> void
        | (
          ?Anthropic::Models::invalid_request_error | Anthropic::BaseModel data
        ) -> void

      def to_hash: -> Anthropic::Models::invalid_request_error
    end
  end
end
