module Anthropic
  module Models
    type message_count_tokens_params =
      {
        messages: ::Array[Anthropic::Models::MessageParam],
        model: Anthropic::Models::model,
        system_: Anthropic::Models::MessageCountTokensParams::system_,
        thinking: Anthropic::Models::thinking_config_param,
        tool_choice: Anthropic::Models::tool_choice,
        tools: ::Array[Anthropic::Models::message_count_tokens_tool]
      }
      & Anthropic::request_parameters

    class MessageCountTokensParams < Anthropic::BaseModel
      extend Anthropic::RequestParameters::Converter
      include Anthropic::RequestParameters

      attr_accessor messages: ::Array[Anthropic::Models::MessageParam]

      attr_accessor model: Anthropic::Models::model

      attr_reader system_: Anthropic::Models::MessageCountTokensParams::system_?

      def system_=: (
        Anthropic::Models::MessageCountTokensParams::system_
      ) -> Anthropic::Models::MessageCountTokensParams::system_

      attr_reader thinking: Anthropic::Models::thinking_config_param?

      def thinking=: (
        Anthropic::Models::thinking_config_param
      ) -> Anthropic::Models::thinking_config_param

      attr_reader tool_choice: Anthropic::Models::tool_choice?

      def tool_choice=: (
        Anthropic::Models::tool_choice
      ) -> Anthropic::Models::tool_choice

      attr_reader tools: ::Array[Anthropic::Models::message_count_tokens_tool]?

      def tools=: (
        ::Array[Anthropic::Models::message_count_tokens_tool]
      ) -> ::Array[Anthropic::Models::message_count_tokens_tool]

      def initialize: (
        messages: ::Array[Anthropic::Models::MessageParam],
        model: Anthropic::Models::model,
        ?system_: Anthropic::Models::MessageCountTokensParams::system_,
        ?thinking: Anthropic::Models::thinking_config_param,
        ?tool_choice: Anthropic::Models::tool_choice,
        ?tools: ::Array[Anthropic::Models::message_count_tokens_tool],
        ?request_options: Anthropic::request_opts
      ) -> void

      def to_hash: -> Anthropic::Models::message_count_tokens_params

      type system_ = String | ::Array[Anthropic::Models::TextBlockParam]

      module System
        extend Anthropic::Union

        def self?.variants: -> [String, ::Array[Anthropic::Models::TextBlockParam]]

        type text_block_param_array = ::Array[Anthropic::Models::TextBlockParam]

        TextBlockParamArray: text_block_param_array
      end
    end
  end
end
