module Anthropic
  module Models
    type message_count_tokens_tool =
      Anthropic::Models::Tool
      | Anthropic::Models::ToolBash20250124
      | Anthropic::Models::ToolTextEditor20250124

    module MessageCountTokensTool
      extend Anthropic::Union

      def self?.variants: -> [Anthropic::Models::Tool, Anthropic::Models::ToolBash20250124, Anthropic::Models::ToolTextEditor20250124]
    end
  end
end
