module Anthropic
  module Models
    type message_param =
      {
        content: Anthropic::MessageParam::content,
        role: Anthropic::MessageParam::role
      }

    class MessageParam < Anthropic::Internal::Type::BaseModel
      attr_accessor content: Anthropic::MessageParam::content

      attr_accessor role: Anthropic::MessageParam::role

      def initialize: (
        content: Anthropic::MessageParam::content,
        role: Anthropic::MessageParam::role
      ) -> void

      type content = String | ::Array[Anthropic::Models::content_block_param]

      module Content
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> ::Array[Anthropic::MessageParam::content]

        ContentBlockParamArray: Anthropic::Internal::Type::Converter
      end

      type role = :user | :assistant

      module Role
        extend Anthropic::Internal::Type::Enum

        USER: :user
        ASSISTANT: :assistant

        def self?.values: -> ::Array[Anthropic::MessageParam::role]
      end
    end
  end
end
