module Anthropic
  module Models
    type model_line = :haiku | :sonnet | :opus | :fable | :mythos

    module ModelLine
      extend Anthropic::Internal::Type::Enum

      HAIKU: :haiku
      SONNET: :sonnet
      OPUS: :opus
      FABLE: :fable
      MYTHOS: :mythos

      def self?.values: -> ::Array[Anthropic::Models::model_line]
    end
  end
end
