module Anthropic
  module Models
    type model_retrieve_params = {  } & Anthropic::request_parameters

    class ModelRetrieveParams < Anthropic::BaseModel
      extend Anthropic::RequestParameters::Converter
      include Anthropic::RequestParameters

      def initialize:
        (request_options: Anthropic::request_opts) -> void
        | (
          ?Anthropic::Models::model_retrieve_params | Anthropic::BaseModel data
        ) -> void

      def to_h: -> Anthropic::Models::model_retrieve_params
    end
  end
end
