module Anthropic
  module Models
    type model_info =
      {
        id: String,
        capabilities: Anthropic::ModelCapabilities?,
        created_at: Time,
        deprecated_at: Time?,
        display_name: String,
        lifecycle: Anthropic::Models::ModelInfo::lifecycle,
        line: Anthropic::Models::model_line?,
        max_input_tokens: Integer?,
        max_tokens: Integer?,
        retires_at: Time?,
        type: :model
      }

    class ModelInfo < Anthropic::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor capabilities: Anthropic::ModelCapabilities?

      attr_accessor created_at: Time

      attr_accessor deprecated_at: Time?

      attr_accessor display_name: String

      attr_accessor lifecycle: Anthropic::Models::ModelInfo::lifecycle

      attr_accessor line: Anthropic::Models::model_line?

      attr_accessor max_input_tokens: Integer?

      attr_accessor max_tokens: Integer?

      attr_accessor retires_at: Time?

      attr_accessor type: :model

      def initialize: (
        id: String,
        capabilities: Anthropic::ModelCapabilities?,
        created_at: Time,
        deprecated_at: Time?,
        display_name: String,
        lifecycle: Anthropic::Models::ModelInfo::lifecycle,
        line: Anthropic::Models::model_line?,
        max_input_tokens: Integer?,
        max_tokens: Integer?,
        retires_at: Time?,
        ?type: :model
      ) -> void

      def to_hash: -> {
        id: String,
        capabilities: Anthropic::ModelCapabilities?,
        created_at: Time,
        deprecated_at: Time?,
        display_name: String,
        lifecycle: Anthropic::Models::ModelInfo::lifecycle,
        line: Anthropic::Models::model_line?,
        max_input_tokens: Integer?,
        max_tokens: Integer?,
        retires_at: Time?,
        type: :model
      }

      type lifecycle = :active | :deprecated | :retired

      module Lifecycle
        extend Anthropic::Internal::Type::Enum

        ACTIVE: :active
        DEPRECATED: :deprecated
        RETIRED: :retired

        def self?.values: -> ::Array[Anthropic::Models::ModelInfo::lifecycle]
      end
    end
  end
end
