module Anthropic
  module Models
    type model_retrieve_params = {  } & Anthropic::request_parameters

    class ModelRetrieveParams < Anthropic::BaseModel
      extend Anthropic::Type::RequestParameters::Converter
      include Anthropic::RequestParameters

      def initialize: (?request_options: Anthropic::request_opts) -> void

      def to_hash: -> Anthropic::Models::model_retrieve_params
    end
  end
end
