module Anthropic
  module Models
    type model_info =
      { id: String, created_at: Time, display_name: String, type: :model }

    class ModelInfo < Anthropic::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor display_name: String

      attr_accessor type: :model

      def initialize:
        (
          id: String,
          created_at: Time,
          display_name: String,
          type: :model
        ) -> void
        | (?Anthropic::Models::model_info | Anthropic::BaseModel data) -> void

      def to_hash: -> Anthropic::Models::model_info
    end
  end
end
