module Anthropic
  module Models
    type raw_message_stream_event =
      Anthropic::Models::RawMessageStartEvent
      | Anthropic::Models::RawMessageDeltaEvent
      | Anthropic::Models::RawMessageStopEvent
      | Anthropic::Models::RawContentBlockStartEvent
      | Anthropic::Models::RawContentBlockDeltaEvent
      | Anthropic::Models::RawContentBlockStopEvent

    module RawMessageStreamEvent
      extend Anthropic::Union

      def self.variants: -> [Anthropic::Models::RawMessageStartEvent, Anthropic::Models::RawMessageDeltaEvent, Anthropic::Models::RawMessageStopEvent, Anthropic::Models::RawContentBlockStartEvent, Anthropic::Models::RawContentBlockDeltaEvent, Anthropic::Models::RawContentBlockStopEvent]
    end
  end
end
