module Anthropic
  module Models
    type raw_message_delta_event =
      {
        delta: Anthropic::Models::RawMessageDeltaEvent::Delta,
        type: :message_delta,
        usage: Anthropic::Models::MessageDeltaUsage
      }

    class RawMessageDeltaEvent < Anthropic::BaseModel
      attr_accessor delta: Anthropic::Models::RawMessageDeltaEvent::Delta

      attr_accessor type: :message_delta

      attr_accessor usage: Anthropic::Models::MessageDeltaUsage

      def initialize: (
        delta: Anthropic::Models::RawMessageDeltaEvent::Delta,
        usage: Anthropic::Models::MessageDeltaUsage,
        ?type: :message_delta
      ) -> void

      def to_hash: -> Anthropic::Models::raw_message_delta_event

      type delta =
        { stop_reason: Anthropic::Models::stop_reason?, stop_sequence: String? }

      class Delta < Anthropic::BaseModel
        attr_accessor stop_reason: Anthropic::Models::stop_reason?

        attr_accessor stop_sequence: String?

        def initialize: (
          stop_reason: Anthropic::Models::stop_reason?,
          stop_sequence: String?
        ) -> void

        def to_hash: -> Anthropic::Models::RawMessageDeltaEvent::delta
      end
    end
  end
end
