module Anthropic
  module Models
    type raw_message_start_event =
      { message: Anthropic::Models::Message, type: :message_start }

    class RawMessageStartEvent < Anthropic::BaseModel
      attr_accessor message: Anthropic::Models::Message

      attr_accessor type: :message_start

      def initialize: (
        message: Anthropic::Models::Message,
        ?type: :message_start
      ) -> void

      def to_hash: -> Anthropic::Models::raw_message_start_event
    end
  end
end
