module Anthropic
  module Models
    type raw_content_block_delta_event =
      {
        delta: Anthropic::Models::RawContentBlockDeltaEvent::delta,
        index: Integer,
        type: :content_block_delta
      }

    class RawContentBlockDeltaEvent < Anthropic::BaseModel
      attr_accessor delta: Anthropic::Models::RawContentBlockDeltaEvent::delta

      attr_accessor index: Integer

      attr_accessor type: :content_block_delta

      def initialize:
        (
          delta: Anthropic::Models::RawContentBlockDeltaEvent::delta,
          index: Integer,
          type: :content_block_delta
        ) -> void
        | (
          ?Anthropic::Models::raw_content_block_delta_event
          | Anthropic::BaseModel data
        ) -> void

      def to_hash: -> Anthropic::Models::raw_content_block_delta_event

      type delta =
        Anthropic::Models::TextDelta
        | Anthropic::Models::InputJSONDelta
        | Anthropic::Models::CitationsDelta
        | Anthropic::Models::ThinkingDelta
        | Anthropic::Models::SignatureDelta

      class Delta < Anthropic::Union
        def self.variants: -> [Anthropic::Models::TextDelta, Anthropic::Models::InputJSONDelta, Anthropic::Models::CitationsDelta, Anthropic::Models::ThinkingDelta, Anthropic::Models::SignatureDelta]
      end
    end
  end
end
