module Anthropic
  module Models
    type text_citation_param =
      Anthropic::Models::CitationCharLocationParam
      | Anthropic::Models::CitationPageLocationParam
      | Anthropic::Models::CitationContentBlockLocationParam

    module TextCitationParam
      extend Anthropic::Internal::Type::Union

      def self?.variants: -> [Anthropic::Models::CitationCharLocationParam, Anthropic::Models::CitationPageLocationParam, Anthropic::Models::CitationContentBlockLocationParam]
    end
  end
end
