module Anthropic
  module Models
    type thinking_config_between_tools = { type: :between_tools }

    class ThinkingConfigBetweenTools < Anthropic::Internal::Type::BaseModel
      attr_accessor type: :between_tools

      def initialize: (?type: :between_tools) -> void

      def to_hash: -> { type: :between_tools }
    end
  end
end
