module Anthropic
  module Models
    type tool_choice =
      Anthropic::Models::ToolChoiceAuto
      | Anthropic::Models::ToolChoiceAny
      | Anthropic::Models::ToolChoiceTool
      | Anthropic::Models::ToolChoiceNone

    module ToolChoice
      extend Anthropic::Union

      def self.variants: -> [Anthropic::Models::ToolChoiceAuto, Anthropic::Models::ToolChoiceAny, Anthropic::Models::ToolChoiceTool, Anthropic::Models::ToolChoiceNone]
    end
  end
end
