module Anthropic
  module Models
    type tool_union =
      Anthropic::Models::Tool
      | Anthropic::Models::ToolBash20250124
      | Anthropic::Models::ToolTextEditor20250124

    module ToolUnion
      extend Anthropic::Union

      def self?.variants: -> [Anthropic::Models::Tool, Anthropic::Models::ToolBash20250124, Anthropic::Models::ToolTextEditor20250124]
    end
  end
end
