module Anthropic
  module Models
    type tool_union =
      Anthropic::Models::ToolBash20250124
      | Anthropic::Models::ToolTextEditor20250124
      | Anthropic::Models::Tool

    class ToolUnion < Anthropic::Union
      private def self.variants: -> [[nil, Anthropic::Models::ToolBash20250124], [nil, Anthropic::Models::ToolTextEditor20250124], [nil, Anthropic::Models::Tool]]
    end
  end
end
