module Anthropic
  module Models
    type tool_choice_tool =
      { name: String, type: :tool, disable_parallel_tool_use: bool }

    class ToolChoiceTool < Anthropic::BaseModel
      attr_accessor name: String

      attr_accessor type: :tool

      attr_reader disable_parallel_tool_use: bool?

      def disable_parallel_tool_use=: (bool) -> bool

      def initialize: (
        name: String,
        ?disable_parallel_tool_use: bool,
        ?type: :tool
      ) -> void

      def to_hash: -> Anthropic::Models::tool_choice_tool
    end
  end
end
