module Anthropic
  module Models
    type tool_bash20250124 =
      {
        name: :bash,
        type: :bash_20250124,
        cache_control: Anthropic::CacheControlEphemeral?,
        strict: bool
      }

    class ToolBash20250124 < Anthropic::Internal::Type::BaseModel
      attr_accessor name: :bash

      attr_accessor type: :bash_20250124

      attr_accessor cache_control: Anthropic::CacheControlEphemeral?

      attr_reader strict: bool?

      def strict=: (bool) -> bool

      def initialize: (
        ?cache_control: Anthropic::CacheControlEphemeral?,
        ?strict: bool,
        ?name: :bash,
        ?type: :bash_20250124
      ) -> void

      def to_hash: -> {
        name: :bash,
        type: :bash_20250124,
        cache_control: Anthropic::CacheControlEphemeral?,
        strict: bool
      }
    end
  end
end
