module Anthropic
  module Models
    module BetaContentBlockSourceContent = Beta::BetaContentBlockSourceContent

    module Beta
      type beta_content_block_source_content =
        Anthropic::Models::Beta::BetaTextBlockParam
        | Anthropic::Models::Beta::BetaImageBlockParam

      module BetaContentBlockSourceContent
        extend Anthropic::Union

        def self?.variants: -> [Anthropic::Models::Beta::BetaTextBlockParam, Anthropic::Models::Beta::BetaImageBlockParam]
      end
    end
  end
end
