module Anthropic
  module Models
    class BetaUserProfile = Beta::BetaUserProfile

    module Beta
      type beta_user_profile =
        {
          id: String,
          created_at: Time,
          metadata: ::Hash[Symbol, String],
          trust_grants: ::Hash[Symbol, Anthropic::Beta::BetaUserProfileTrustGrant],
          type: Anthropic::Models::Beta::BetaUserProfile::type_,
          updated_at: Time,
          external_id: String?
        }

      class BetaUserProfile < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor metadata: ::Hash[Symbol, String]

        attr_accessor trust_grants: ::Hash[Symbol, Anthropic::Beta::BetaUserProfileTrustGrant]

        attr_accessor type: Anthropic::Models::Beta::BetaUserProfile::type_

        attr_accessor updated_at: Time

        attr_accessor external_id: String?

        def initialize: (
          id: String,
          created_at: Time,
          metadata: ::Hash[Symbol, String],
          trust_grants: ::Hash[Symbol, Anthropic::Beta::BetaUserProfileTrustGrant],
          type: Anthropic::Models::Beta::BetaUserProfile::type_,
          updated_at: Time,
          ?external_id: String?
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          metadata: ::Hash[Symbol, String],
          trust_grants: ::Hash[Symbol, Anthropic::Beta::BetaUserProfileTrustGrant],
          type: Anthropic::Models::Beta::BetaUserProfile::type_,
          updated_at: Time,
          external_id: String?
        }

        type type_ = :user_profile

        module Type
          extend Anthropic::Internal::Type::Enum

          USER_PROFILE: :user_profile

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaUserProfile::type_]
        end
      end
    end
  end
end
