module Anthropic
  module Models
    module BetaTextCitation = Beta::BetaTextCitation

    module Beta
      type beta_text_citation =
        Anthropic::Models::Beta::BetaCitationCharLocation
        | Anthropic::Models::Beta::BetaCitationPageLocation
        | Anthropic::Models::Beta::BetaCitationContentBlockLocation

      module BetaTextCitation
        extend Anthropic::Union

        def self.variants: -> [Anthropic::Models::Beta::BetaCitationCharLocation, Anthropic::Models::Beta::BetaCitationPageLocation, Anthropic::Models::Beta::BetaCitationContentBlockLocation]
      end
    end
  end
end
