module Anthropic
  module Models
    class BetaBrowserLeftMouseUpToolUseBlock = Beta::BetaBrowserLeftMouseUpToolUseBlock

    module Beta
      type beta_browser_left_mouse_up_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftMouseUpInput,
          name: :left_mouse_up,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserLeftMouseUpToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserLeftMouseUpInput

        attr_accessor name: :left_mouse_up

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftMouseUpInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :left_mouse_up,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftMouseUpInput,
          name: :left_mouse_up,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
