module Anthropic
  module Models
    module BetaContentBlockParam = Beta::BetaContentBlockParam

    module Beta
      type beta_content_block_param =
        Anthropic::Models::Beta::BetaTextBlockParam
        | Anthropic::Models::Beta::BetaImageBlockParam
        | Anthropic::Models::Beta::BetaToolUseBlockParam
        | Anthropic::Models::Beta::BetaToolResultBlockParam
        | Anthropic::Models::Beta::BetaBase64PDFBlock
        | Anthropic::Models::Beta::BetaThinkingBlockParam
        | Anthropic::Models::Beta::BetaRedactedThinkingBlockParam

      module BetaContentBlockParam
        extend Anthropic::Union

        def self?.variants: -> [Anthropic::Models::Beta::BetaTextBlockParam, Anthropic::Models::Beta::BetaImageBlockParam, Anthropic::Models::Beta::BetaToolUseBlockParam, Anthropic::Models::Beta::BetaToolResultBlockParam, Anthropic::Models::Beta::BetaBase64PDFBlock, Anthropic::Models::Beta::BetaThinkingBlockParam, Anthropic::Models::Beta::BetaRedactedThinkingBlockParam]
      end
    end
  end
end
