module Anthropic
  module Models
    class BetaBrowserScreenshotInput = Beta::BetaBrowserScreenshotInput

    module Beta
      type beta_browser_screenshot_input = { tab_id: String? }

      class BetaBrowserScreenshotInput < Anthropic::Internal::Type::BaseModel
        attr_accessor tab_id: String?

        def initialize: (?tab_id: String?) -> void

        def to_hash: -> { tab_id: String? }
      end
    end
  end
end
