module Anthropic
  module Models
    class BetaBrowserDoubleClickToolUseBlock = Beta::BetaBrowserDoubleClickToolUseBlock

    module Beta
      type beta_browser_double_click_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserDoubleClickInput,
          name: :double_click,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserDoubleClickToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserDoubleClickInput

        attr_accessor name: :double_click

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserDoubleClickInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :double_click,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserDoubleClickInput,
          name: :double_click,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
