module Anthropic
  module Models
    class BetaBrowserFormInputToolUseBlock = Beta::BetaBrowserFormInputToolUseBlock

    module Beta
      type beta_browser_form_input_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserFormInputInput,
          name: :form_input,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserFormInputToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserFormInputInput

        attr_accessor name: :form_input

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserFormInputInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :form_input,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserFormInputInput,
          name: :form_input,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
