module Anthropic
  module Models
    module BetaRawContentBlockDelta = Beta::BetaRawContentBlockDelta

    module Beta
      type beta_raw_content_block_delta =
        Anthropic::Models::Beta::BetaTextDelta
        | Anthropic::Models::Beta::BetaInputJSONDelta
        | Anthropic::Models::Beta::BetaCitationsDelta
        | Anthropic::Models::Beta::BetaThinkingDelta
        | Anthropic::Models::Beta::BetaSignatureDelta

      module BetaRawContentBlockDelta
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> [Anthropic::Models::Beta::BetaTextDelta, Anthropic::Models::Beta::BetaInputJSONDelta, Anthropic::Models::Beta::BetaCitationsDelta, Anthropic::Models::Beta::BetaThinkingDelta, Anthropic::Models::Beta::BetaSignatureDelta]
      end
    end
  end
end
