module Anthropic
  module Models
    class BetaManagedAgentsWebFetchURLSourceToolReference = Beta::BetaManagedAgentsWebFetchURLSourceToolReference

    module Beta
      type beta_managed_agents_web_fetch_url_source_tool_reference =
        { name: String, type: :tool_reference }

      class BetaManagedAgentsWebFetchURLSourceToolReference < Anthropic::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: :tool_reference

        def initialize: (name: String, ?type: :tool_reference) -> void

        def to_hash: -> { name: String, type: :tool_reference }
      end
    end
  end
end
