module Anthropic
  module Models
    module BetaRawMessageStreamEvent = Beta::BetaRawMessageStreamEvent

    module Beta
      type beta_raw_message_stream_event =
        Anthropic::Models::Beta::BetaRawMessageStartEvent
        | Anthropic::Models::Beta::BetaRawMessageDeltaEvent
        | Anthropic::Models::Beta::BetaRawMessageStopEvent
        | Anthropic::Models::Beta::BetaRawContentBlockStartEvent
        | Anthropic::Models::Beta::BetaRawContentBlockDeltaEvent
        | Anthropic::Models::Beta::BetaRawContentBlockStopEvent

      module BetaRawMessageStreamEvent
        extend Anthropic::Union

        def self.variants: -> [Anthropic::Models::Beta::BetaRawMessageStartEvent, Anthropic::Models::Beta::BetaRawMessageDeltaEvent, Anthropic::Models::Beta::BetaRawMessageStopEvent, Anthropic::Models::Beta::BetaRawContentBlockStartEvent, Anthropic::Models::Beta::BetaRawContentBlockDeltaEvent, Anthropic::Models::Beta::BetaRawContentBlockStopEvent]
      end
    end
  end
end
