module Anthropic
  module Models
    
    class BetaContentBlockSourceContent = Beta::BetaContentBlockSourceContent

    module Beta
      type beta_content_block_source_content =
        Anthropic::Models::Beta::BetaTextBlockParam
        | Anthropic::Models::Beta::BetaImageBlockParam

      class BetaContentBlockSourceContent < Anthropic::Union
        private def self.variants: -> [[:text, Anthropic::Models::Beta::BetaTextBlockParam], [:image, Anthropic::Models::Beta::BetaImageBlockParam]]
      end
    end
  end
end
