module Anthropic
  module Models
    module BetaManagedAgentsWebFetchURLSourceToolFilterParams = Beta::BetaManagedAgentsWebFetchURLSourceToolFilterParams

    module Beta
      type beta_managed_agents_web_fetch_url_source_tool_filter_params =
        Anthropic::Models::Beta::beta_managed_agents_web_fetch_url_source_shorthand
        | Anthropic::Models::Beta::beta_managed_agents_web_fetch_url_source_tool_filter

      module BetaManagedAgentsWebFetchURLSourceToolFilterParams
        extend Anthropic::Internal::Type::Union

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_web_fetch_url_source_tool_filter_params]
      end
    end
  end
end
