module Anthropic
  module Models
    module BetaThinkingConfigParam = Beta::BetaThinkingConfigParam

    module Beta
      type beta_thinking_config_param =
        Anthropic::Models::Beta::BetaThinkingConfigEnabled
        | Anthropic::Models::Beta::BetaThinkingConfigDisabled

      module BetaThinkingConfigParam
        extend Anthropic::Union

        def self?.variants: -> [Anthropic::Models::Beta::BetaThinkingConfigEnabled, Anthropic::Models::Beta::BetaThinkingConfigDisabled]
      end
    end
  end
end
