module Anthropic
  module Models
    
    class BetaUsage = Beta::BetaUsage

    module Beta
      type beta_usage =
        {
          cache_creation_input_tokens: Integer?,
          cache_read_input_tokens: Integer?,
          input_tokens: Integer,
          output_tokens: Integer
        }

      class BetaUsage < Anthropic::BaseModel
        attr_accessor cache_creation_input_tokens: Integer?

        attr_accessor cache_read_input_tokens: Integer?

        attr_accessor input_tokens: Integer

        attr_accessor output_tokens: Integer

        def initialize:
          (
            cache_creation_input_tokens: Integer?,
            cache_read_input_tokens: Integer?,
            input_tokens: Integer,
            output_tokens: Integer
          ) -> void
          | (
            ?Anthropic::Models::Beta::beta_usage | Anthropic::BaseModel data
          ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_usage
      end
    end
  end
end
