module Anthropic
  module Models
    
    class BetaBase64PDFBlock = Beta::BetaBase64PDFBlock

    module Beta
      type beta_base64_pdf_block =
        {
          source: Anthropic::Models::Beta::BetaBase64PDFBlock::source,
          type: :document,
          cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?,
          citations: Anthropic::Models::Beta::BetaCitationsConfigParam,
          context: String?,
          title: String?
        }

      class BetaBase64PDFBlock < Anthropic::BaseModel
        attr_accessor source: Anthropic::Models::Beta::BetaBase64PDFBlock::source

        attr_accessor type: :document

        attr_accessor cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?

        attr_reader citations: Anthropic::Models::Beta::BetaCitationsConfigParam?

        def citations=: (
          Anthropic::Models::Beta::BetaCitationsConfigParam
        ) -> Anthropic::Models::Beta::BetaCitationsConfigParam

        attr_accessor context: String?

        attr_accessor title: String?

        def initialize: (
          source: Anthropic::Models::Beta::BetaBase64PDFBlock::source,
          ?cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?,
          ?citations: Anthropic::Models::Beta::BetaCitationsConfigParam,
          ?context: String?,
          ?title: String?,
          ?type: :document
        ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_base64_pdf_block

        type source =
          Anthropic::Models::Beta::BetaBase64PDFSource
          | Anthropic::Models::Beta::BetaPlainTextSource
          | Anthropic::Models::Beta::BetaContentBlockSource
          | Anthropic::Models::Beta::BetaURLPDFSource

        class Source < Anthropic::Union
          def self.variants: -> [Anthropic::Models::Beta::BetaBase64PDFSource, Anthropic::Models::Beta::BetaPlainTextSource, Anthropic::Models::Beta::BetaContentBlockSource, Anthropic::Models::Beta::BetaURLPDFSource]
        end
      end
    end
  end
end
