module Anthropic
  module Models
    class BetaRawMessageDeltaEvent = Beta::BetaRawMessageDeltaEvent

    module Beta
      type beta_raw_message_delta_event =
        {
          delta: Anthropic::Beta::BetaRawMessageDeltaEvent::Delta,
          type: :message_delta,
          usage: Anthropic::Beta::BetaMessageDeltaUsage
        }

      class BetaRawMessageDeltaEvent < Anthropic::Internal::Type::BaseModel
        attr_accessor delta: Anthropic::Beta::BetaRawMessageDeltaEvent::Delta

        attr_accessor type: :message_delta

        attr_accessor usage: Anthropic::Beta::BetaMessageDeltaUsage

        def initialize: (
          delta: Anthropic::Beta::BetaRawMessageDeltaEvent::Delta,
          usage: Anthropic::Beta::BetaMessageDeltaUsage,
          ?type: :message_delta
        ) -> void

        type delta =
          {
            stop_reason: Anthropic::Models::Beta::beta_stop_reason?,
            stop_sequence: String?
          }

        class Delta < Anthropic::Internal::Type::BaseModel
          attr_accessor stop_reason: Anthropic::Models::Beta::beta_stop_reason?

          attr_accessor stop_sequence: String?

          def initialize: (
            stop_reason: Anthropic::Models::Beta::beta_stop_reason?,
            stop_sequence: String?
          ) -> void
        end
      end
    end
  end
end
