module Anthropic
  module Models
    class BetaComputerLeftClickToolUseBlock = Beta::BetaComputerLeftClickToolUseBlock

    module Beta
      type beta_computer_left_click_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaComputerLeftClickInput,
          name: :left_click,
          toolset_name: :computer,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaComputerLeftClickToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaComputerLeftClickInput

        attr_accessor name: :left_click

        attr_accessor toolset_name: :computer

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaComputerLeftClickInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :left_click,
          ?toolset_name: :computer,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaComputerLeftClickInput,
          name: :left_click,
          toolset_name: :computer,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
