module Anthropic
  module Models
    
    class BetaToolUnion = Beta::BetaToolUnion

    module Beta
      type beta_tool_union =
        Anthropic::Models::Beta::BetaTool
        | Anthropic::Models::Beta::BetaToolComputerUse20241022
        | Anthropic::Models::Beta::BetaToolBash20241022
        | Anthropic::Models::Beta::BetaToolTextEditor20241022
        | Anthropic::Models::Beta::BetaToolComputerUse20250124
        | Anthropic::Models::Beta::BetaToolBash20250124
        | Anthropic::Models::Beta::BetaToolTextEditor20250124

      class BetaToolUnion < Anthropic::Union
        private def self.variants: -> [[nil, Anthropic::Models::Beta::BetaTool], [nil, Anthropic::Models::Beta::BetaToolComputerUse20241022], [nil, Anthropic::Models::Beta::BetaToolBash20241022], [nil, Anthropic::Models::Beta::BetaToolTextEditor20241022], [nil, Anthropic::Models::Beta::BetaToolComputerUse20250124], [nil, Anthropic::Models::Beta::BetaToolBash20250124], [nil, Anthropic::Models::Beta::BetaToolTextEditor20250124]]
      end
    end
  end
end
