module Anthropic
  module Models
    class BetaBrowserHoverToolUseBlock = Beta::BetaBrowserHoverToolUseBlock

    module Beta
      type beta_browser_hover_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserHoverInput,
          name: :hover,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserHoverToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserHoverInput

        attr_accessor name: :hover

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserHoverInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :hover,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserHoverInput,
          name: :hover,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
