module Anthropic
  module Models
    class BetaManagedAgentsMultiagentInlineAgentsDisabledParams = Beta::BetaManagedAgentsMultiagentInlineAgentsDisabledParams

    module Beta
      type beta_managed_agents_multiagent_inline_agents_disabled_params =
        { type: :disabled }

      class BetaManagedAgentsMultiagentInlineAgentsDisabledParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
