module Anthropic
  module Models
    class BetaComputerHoldKeyInput = Beta::BetaComputerHoldKeyInput

    module Beta
      type beta_computer_hold_key_input = { duration: Integer, text: String }

      class BetaComputerHoldKeyInput < Anthropic::Internal::Type::BaseModel
        attr_accessor duration: Integer

        attr_accessor text: String

        def initialize: (duration: Integer, text: String) -> void

        def to_hash: -> { duration: Integer, text: String }
      end
    end
  end
end
