module Anthropic
  module Models
    class BetaBrowserHoldKeyInput = Beta::BetaBrowserHoldKeyInput

    module Beta
      type beta_browser_hold_key_input =
        { duration: Float, text: String, tab_id: String? }

      class BetaBrowserHoldKeyInput < Anthropic::Internal::Type::BaseModel
        attr_accessor duration: Float

        attr_accessor text: String

        attr_accessor tab_id: String?

        def initialize: (
          duration: Float,
          text: String,
          ?tab_id: String?
        ) -> void

        def to_hash: -> { duration: Float, text: String, tab_id: String? }
      end
    end
  end
end
