module Anthropic
  module Models
    class BetaCompactionBlock = Beta::BetaCompactionBlock

    module Beta
      type beta_compaction_block =
        {
          content: String?,
          encrypted_content: String?,
          type: :compaction,
          signature: String?
        }

      class BetaCompactionBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor content: String?

        attr_accessor encrypted_content: String?

        attr_accessor type: :compaction

        attr_accessor signature: String?

        def initialize: (
          content: String?,
          encrypted_content: String?,
          ?signature: String?,
          ?type: :compaction
        ) -> void

        def to_hash: -> {
          content: String?,
          encrypted_content: String?,
          type: :compaction,
          signature: String?
        }
      end
    end
  end
end
