module Anthropic
  module Models
    
    class BetaImageBlockParam = Beta::BetaImageBlockParam

    module Beta
      type beta_image_block_param =
        {
          source: Anthropic::Models::Beta::BetaImageBlockParam::source,
          type: :image,
          cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?
        }

      class BetaImageBlockParam < Anthropic::BaseModel
        attr_accessor source: Anthropic::Models::Beta::BetaImageBlockParam::source

        attr_accessor type: :image

        attr_accessor cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?

        def initialize:
          (
            source: Anthropic::Models::Beta::BetaImageBlockParam::source,
            cache_control: Anthropic::Models::Beta::BetaCacheControlEphemeral?,
            type: :image
          ) -> void
          | (
            ?Anthropic::Models::Beta::beta_image_block_param
            | Anthropic::BaseModel data
          ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_image_block_param

        type source =
          Anthropic::Models::Beta::BetaBase64ImageSource
          | Anthropic::Models::Beta::BetaURLImageSource

        class Source < Anthropic::Union
          private def self.variants: -> [[:base64, Anthropic::Models::Beta::BetaBase64ImageSource], [:url, Anthropic::Models::Beta::BetaURLImageSource]]
        end
      end
    end
  end
end
