module Anthropic
  module Models
    class BetaManagedAgentsMultiagentSubagentsDisabled = Beta::BetaManagedAgentsMultiagentSubagentsDisabled

    module Beta
      type beta_managed_agents_multiagent_subagents_disabled =
        { type: :disabled }

      class BetaManagedAgentsMultiagentSubagentsDisabled < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
