module Anthropic
  module Models
    module BetaContentBlock = Beta::BetaContentBlock

    module Beta
      type beta_content_block =
        Anthropic::Models::Beta::BetaTextBlock
        | Anthropic::Models::Beta::BetaToolUseBlock
        | Anthropic::Models::Beta::BetaThinkingBlock
        | Anthropic::Models::Beta::BetaRedactedThinkingBlock

      module BetaContentBlock
        extend Anthropic::Union

        def self.variants: -> [Anthropic::Models::Beta::BetaTextBlock, Anthropic::Models::Beta::BetaToolUseBlock, Anthropic::Models::Beta::BetaThinkingBlock, Anthropic::Models::Beta::BetaRedactedThinkingBlock]
      end
    end
  end
end
