module Anthropic
  module Models
    
    class BetaCitationsConfigParam = Beta::BetaCitationsConfigParam

    module Beta
      type beta_citations_config_param = { enabled: bool }

      class BetaCitationsConfigParam < Anthropic::BaseModel
        attr_reader enabled: bool?

        def enabled=: (bool) -> void

        def initialize:
          (enabled: bool) -> void
          | (
            ?Anthropic::Models::Beta::beta_citations_config_param
            | Anthropic::BaseModel data
          ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_citations_config_param
      end
    end
  end
end
