module Anthropic
  module Models
    class BetaComputerZoomToolUseBlock = Beta::BetaComputerZoomToolUseBlock

    module Beta
      type beta_computer_zoom_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaComputerZoomInput,
          name: :zoom,
          toolset_name: :computer,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaComputerZoomToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaComputerZoomInput

        attr_accessor name: :zoom

        attr_accessor toolset_name: :computer

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaComputerZoomInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :zoom,
          ?toolset_name: :computer,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaComputerZoomInput,
          name: :zoom,
          toolset_name: :computer,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
