module Anthropic
  module Models
    class BetaManagedAgentsWebFetchURLSourceAll = Beta::BetaManagedAgentsWebFetchURLSourceAll

    module Beta
      type beta_managed_agents_web_fetch_url_source_all = { type: :all }

      class BetaManagedAgentsWebFetchURLSourceAll < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :all

        def initialize: (?type: :all) -> void

        def to_hash: -> { type: :all }
      end
    end
  end
end
