module Anthropic
  module Models
    
    class BetaToolChoiceTool = Beta::BetaToolChoiceTool

    module Beta
      type beta_tool_choice_tool =
        { name: String, type: :tool, disable_parallel_tool_use: bool }

      class BetaToolChoiceTool < Anthropic::BaseModel
        attr_accessor name: String

        attr_accessor type: :tool

        attr_reader disable_parallel_tool_use: bool?

        def disable_parallel_tool_use=: (bool) -> bool

        def initialize:
          (name: String, disable_parallel_tool_use: bool, type: :tool) -> void
          | (
            ?Anthropic::Models::Beta::beta_tool_choice_tool
            | Anthropic::BaseModel data
          ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_tool_choice_tool
      end
    end
  end
end
