module Anthropic
  module Models
    class BetaBrowserReadNetworkInput = Beta::BetaBrowserReadNetworkInput

    module Beta
      type beta_browser_read_network_input = { tab_id: String? }

      class BetaBrowserReadNetworkInput < Anthropic::Internal::Type::BaseModel
        attr_accessor tab_id: String?

        def initialize: (?tab_id: String?) -> void

        def to_hash: -> { tab_id: String? }
      end
    end
  end
end
