module Anthropic
  module Models
    class BetaMemoryTool20250818 = Beta::BetaMemoryTool20250818

    module Beta
      type beta_memory_tool20250818 =
        {
          name: :memory,
          type: :memory_20250818,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          strict: bool
        }

      class BetaMemoryTool20250818 < Anthropic::Internal::Type::BaseModel
        attr_accessor name: :memory

        attr_accessor type: :memory_20250818

        attr_accessor cache_control: Anthropic::Beta::BetaCacheControlEphemeral?

        attr_reader strict: bool?

        def strict=: (bool) -> bool

        def initialize: (
          ?cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          ?strict: bool,
          ?name: :memory,
          ?type: :memory_20250818
        ) -> void

        def to_hash: -> {
          name: :memory,
          type: :memory_20250818,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          strict: bool
        }
      end
    end
  end
end
