module Anthropic
  module Models
    class BetaModelInfo = Beta::BetaModelInfo

    module Beta
      type beta_model_info =
        {
          id: String,
          allowed_fallback_models: ::Array[String]?,
          capabilities: Anthropic::Beta::BetaModelCapabilities?,
          created_at: Time,
          deprecated_at: Time?,
          display_name: String,
          lifecycle: Anthropic::Models::Beta::BetaModelInfo::lifecycle,
          line: Anthropic::Models::Beta::beta_model_line?,
          max_input_tokens: Integer?,
          max_tokens: Integer?,
          retires_at: Time?,
          type: :model
        }

      class BetaModelInfo < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor allowed_fallback_models: ::Array[String]?

        attr_accessor capabilities: Anthropic::Beta::BetaModelCapabilities?

        attr_accessor created_at: Time

        attr_accessor deprecated_at: Time?

        attr_accessor display_name: String

        attr_accessor lifecycle: Anthropic::Models::Beta::BetaModelInfo::lifecycle

        attr_accessor line: Anthropic::Models::Beta::beta_model_line?

        attr_accessor max_input_tokens: Integer?

        attr_accessor max_tokens: Integer?

        attr_accessor retires_at: Time?

        attr_accessor type: :model

        def initialize: (
          id: String,
          allowed_fallback_models: ::Array[String]?,
          capabilities: Anthropic::Beta::BetaModelCapabilities?,
          created_at: Time,
          deprecated_at: Time?,
          display_name: String,
          lifecycle: Anthropic::Models::Beta::BetaModelInfo::lifecycle,
          line: Anthropic::Models::Beta::beta_model_line?,
          max_input_tokens: Integer?,
          max_tokens: Integer?,
          retires_at: Time?,
          ?type: :model
        ) -> void

        def to_hash: -> {
          id: String,
          allowed_fallback_models: ::Array[String]?,
          capabilities: Anthropic::Beta::BetaModelCapabilities?,
          created_at: Time,
          deprecated_at: Time?,
          display_name: String,
          lifecycle: Anthropic::Models::Beta::BetaModelInfo::lifecycle,
          line: Anthropic::Models::Beta::beta_model_line?,
          max_input_tokens: Integer?,
          max_tokens: Integer?,
          retires_at: Time?,
          type: :model
        }

        type lifecycle = :active | :deprecated | :retired

        module Lifecycle
          extend Anthropic::Internal::Type::Enum

          ACTIVE: :active
          DEPRECATED: :deprecated
          RETIRED: :retired

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaModelInfo::lifecycle]
        end
      end
    end
  end
end
