module Anthropic
  module Models
    
    class BetaRawContentBlockStartEvent = Beta::BetaRawContentBlockStartEvent

    module Beta
      type beta_raw_content_block_start_event =
        {
          content_block: Anthropic::Models::Beta::BetaRawContentBlockStartEvent::content_block,
          index: Integer,
          type: :content_block_start
        }

      class BetaRawContentBlockStartEvent < Anthropic::BaseModel
        attr_accessor content_block: Anthropic::Models::Beta::BetaRawContentBlockStartEvent::content_block

        attr_accessor index: Integer

        attr_accessor type: :content_block_start

        def initialize: (
          content_block: Anthropic::Models::Beta::BetaRawContentBlockStartEvent::content_block,
          index: Integer,
          ?type: :content_block_start
        ) -> void

        def to_hash: -> Anthropic::Models::Beta::beta_raw_content_block_start_event

        type content_block =
          Anthropic::Models::Beta::BetaTextBlock
          | Anthropic::Models::Beta::BetaToolUseBlock
          | Anthropic::Models::Beta::BetaThinkingBlock
          | Anthropic::Models::Beta::BetaRedactedThinkingBlock

        class ContentBlock < Anthropic::Union
          def self.variants: -> [Anthropic::Models::Beta::BetaTextBlock, Anthropic::Models::Beta::BetaToolUseBlock, Anthropic::Models::Beta::BetaThinkingBlock, Anthropic::Models::Beta::BetaRedactedThinkingBlock]
        end
      end
    end
  end
end
