module Anthropic
  module Models
    module BetaBrowserScrollDirection = Beta::BetaBrowserScrollDirection

    module Beta
      type beta_browser_scroll_direction = :up | :down | :left | :right

      module BetaBrowserScrollDirection
        extend Anthropic::Internal::Type::Enum

        UP: :up
        DOWN: :down
        LEFT: :left
        RIGHT: :right

        def self?.values: -> ::Array[Anthropic::Models::Beta::beta_browser_scroll_direction]
      end
    end
  end
end
