module Anthropic
  module Models
    class BetaRelayTunnelTransport = Beta::BetaRelayTunnelTransport

    module Beta
      type beta_relay_tunnel_transport =
        { type: :relay, token: Anthropic::Beta::BetaTunnelToken }

      class BetaRelayTunnelTransport < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :relay

        attr_reader token: Anthropic::Beta::BetaTunnelToken?

        def token=: (
          Anthropic::Beta::BetaTunnelToken
        ) -> Anthropic::Beta::BetaTunnelToken

        def initialize: (
          ?token: Anthropic::Beta::BetaTunnelToken,
          ?type: :relay
        ) -> void

        def to_hash: -> {
          type: :relay,
          token: Anthropic::Beta::BetaTunnelToken
        }
      end
    end
  end
end
