module Anthropic
  module Models
    module BetaManagedAgentsWebFetchURLSourceShorthand = Beta::BetaManagedAgentsWebFetchURLSourceShorthand

    module Beta
      type beta_managed_agents_web_fetch_url_source_shorthand = :all | :none

      module BetaManagedAgentsWebFetchURLSourceShorthand
        extend Anthropic::Internal::Type::Enum

        ALL: :all
        NONE: :none

        def self?.values: -> ::Array[Anthropic::Models::Beta::beta_managed_agents_web_fetch_url_source_shorthand]
      end
    end
  end
end
