module Anthropic
  module Models
    class BetaBrowserLeftClickDragToolUseBlock = Beta::BetaBrowserLeftClickDragToolUseBlock

    module Beta
      type beta_browser_left_click_drag_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftClickDragInput,
          name: :left_click_drag,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserLeftClickDragToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserLeftClickDragInput

        attr_accessor name: :left_click_drag

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftClickDragInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :left_click_drag,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserLeftClickDragInput,
          name: :left_click_drag,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
