module Anthropic
  module Models
    module BetaToolChoice = Beta::BetaToolChoice

    module Beta
      type beta_tool_choice =
        Anthropic::Models::Beta::BetaToolChoiceAuto
        | Anthropic::Models::Beta::BetaToolChoiceAny
        | Anthropic::Models::Beta::BetaToolChoiceTool
        | Anthropic::Models::Beta::BetaToolChoiceNone

      module BetaToolChoice
        extend Anthropic::Union

        def self.variants: -> [Anthropic::Models::Beta::BetaToolChoiceAuto, Anthropic::Models::Beta::BetaToolChoiceAny, Anthropic::Models::Beta::BetaToolChoiceTool, Anthropic::Models::Beta::BetaToolChoiceNone]
      end
    end
  end
end
