module Anthropic
  module Models
    module BetaTunnelTransport = Beta::BetaTunnelTransport

    module Beta
      type beta_tunnel_transport =
        Anthropic::Beta::BetaCloudflareTunnelTransport
        | Anthropic::Beta::BetaRelayTunnelTransport

      module BetaTunnelTransport
        extend Anthropic::Internal::Type::Union

        type type_ = :cloudflare | :relay

        module Type
          extend Anthropic::Internal::Type::Enum

          CLOUDFLARE: :cloudflare
          RELAY: :relay

          def self?.values: -> ::Array[Anthropic::Models::Beta::BetaTunnelTransport::type_]
        end

        def self?.variants: -> ::Array[Anthropic::Models::Beta::beta_tunnel_transport]

        def self.new:
          (
            type: :cloudflare | "cloudflare"
          ) -> Anthropic::Beta::BetaCloudflareTunnelTransport
          | (
            type: :relay | "relay",
            ?token: Anthropic::Beta::BetaTunnelToken
          ) -> Anthropic::Beta::BetaRelayTunnelTransport
          | (
            type: Anthropic::Models::Beta::BetaTunnelTransport::type_ | String,
            ?token: Anthropic::Beta::BetaTunnelToken
          ) -> Anthropic::Models::Beta::beta_tunnel_transport
      end
    end
  end
end
