module Anthropic
  module Models
    class BetaContextManagementConfig = Beta::BetaContextManagementConfig

    module Beta
      type beta_context_management_config =
        { edits: ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit] }

      class BetaContextManagementConfig < Anthropic::Internal::Type::BaseModel
        attr_reader edits: ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit]?

        def edits=: (
          ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit]
        ) -> ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit]

        def initialize: (
          ?edits: ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit]
        ) -> void

        def to_hash: -> {
          edits: ::Array[Anthropic::Beta::BetaClearToolUses20250919Edit]
        }
      end
    end
  end
end
