module Anthropic
  module Models
    class BetaManagedAgentsMultiagentWorkflowsDisabled = Beta::BetaManagedAgentsMultiagentWorkflowsDisabled

    module Beta
      type beta_managed_agents_multiagent_workflows_disabled =
        { type: :disabled }

      class BetaManagedAgentsMultiagentWorkflowsDisabled < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
