module Anthropic
  module Models
    class BetaManagedAgentsMultiagentSubagentsDisabledParams = Beta::BetaManagedAgentsMultiagentSubagentsDisabledParams

    module Beta
      type beta_managed_agents_multiagent_subagents_disabled_params =
        { type: :disabled }

      class BetaManagedAgentsMultiagentSubagentsDisabledParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
