module Anthropic
  module Models
    class BetaToolBash20241022 = Beta::BetaToolBash20241022

    module Beta
      type beta_tool_bash20241022 =
        {
          name: :bash,
          type: :bash_20241022,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          strict: bool
        }

      class BetaToolBash20241022 < Anthropic::Internal::Type::BaseModel
        attr_accessor name: :bash

        attr_accessor type: :bash_20241022

        attr_accessor cache_control: Anthropic::Beta::BetaCacheControlEphemeral?

        attr_reader strict: bool?

        def strict=: (bool) -> bool

        def initialize: (
          ?cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          ?strict: bool,
          ?name: :bash,
          ?type: :bash_20241022
        ) -> void

        def to_hash: -> {
          name: :bash,
          type: :bash_20241022,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          strict: bool
        }
      end
    end
  end
end
