module Anthropic
  module Models
    class BetaCodeExecutionTool20250825 = Beta::BetaCodeExecutionTool20250825

    module Beta
      type beta_code_execution_tool20250825 =
        {
          name: :code_execution,
          type: :code_execution_20250825,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?
        }

      class BetaCodeExecutionTool20250825 < Anthropic::Internal::Type::BaseModel
        attr_accessor name: :code_execution

        attr_accessor type: :code_execution_20250825

        attr_accessor cache_control: Anthropic::Beta::BetaCacheControlEphemeral?

        def initialize: (
          ?cache_control: Anthropic::Beta::BetaCacheControlEphemeral?,
          ?name: :code_execution,
          ?type: :code_execution_20250825
        ) -> void

        def to_hash: -> {
          name: :code_execution,
          type: :code_execution_20250825,
          cache_control: Anthropic::Beta::BetaCacheControlEphemeral?
        }
      end
    end
  end
end
