module Anthropic
  module Models
    class BetaManagedAgentsMultiagentWorkflowsDisabledParams = Beta::BetaManagedAgentsMultiagentWorkflowsDisabledParams

    module Beta
      type beta_managed_agents_multiagent_workflows_disabled_params =
        { type: :disabled }

      class BetaManagedAgentsMultiagentWorkflowsDisabledParams < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
