module Anthropic
  module Models
    
    class BetaTextCitationParam = Beta::BetaTextCitationParam

    module Beta
      type beta_text_citation_param =
        Anthropic::Models::Beta::BetaCitationCharLocationParam
        | Anthropic::Models::Beta::BetaCitationPageLocationParam
        | Anthropic::Models::Beta::BetaCitationContentBlockLocationParam

      class BetaTextCitationParam < Anthropic::Union
        def self.variants: -> [Anthropic::Models::Beta::BetaCitationCharLocationParam, Anthropic::Models::Beta::BetaCitationPageLocationParam, Anthropic::Models::Beta::BetaCitationContentBlockLocationParam]
      end
    end
  end
end
