module Anthropic
  module Models
    class BetaCitationsDelta = Beta::BetaCitationsDelta

    module Beta
      type beta_citations_delta =
        {
          citation: Anthropic::Beta::BetaCitationsDelta::citation,
          type: :citations_delta
        }

      class BetaCitationsDelta < Anthropic::Internal::Type::BaseModel
        attr_accessor citation: Anthropic::Beta::BetaCitationsDelta::citation

        attr_accessor type: :citations_delta

        def initialize: (
          citation: Anthropic::Beta::BetaCitationsDelta::citation,
          ?type: :citations_delta
        ) -> void

        type citation =
          Anthropic::Beta::BetaCitationCharLocation
          | Anthropic::Beta::BetaCitationPageLocation
          | Anthropic::Beta::BetaCitationContentBlockLocation

        module Citation
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Beta::BetaCitationsDelta::citation]
        end
      end
    end
  end
end
