module Anthropic
  module Models
    class BetaBrowserMouseMoveToolUseBlock = Beta::BetaBrowserMouseMoveToolUseBlock

    module Beta
      type beta_browser_mouse_move_tool_use_block =
        {
          id: String,
          input: Anthropic::Beta::BetaBrowserMouseMoveInput,
          name: :mouse_move,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }

      class BetaBrowserMouseMoveToolUseBlock < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor input: Anthropic::Beta::BetaBrowserMouseMoveInput

        attr_accessor name: :mouse_move

        attr_accessor toolset_name: :browser

        attr_accessor type: :tool_use

        attr_reader caller_: Anthropic::Models::Beta::beta_tool_use_caller?

        def caller_=: (
          Anthropic::Models::Beta::beta_tool_use_caller
        ) -> Anthropic::Models::Beta::beta_tool_use_caller

        def initialize: (
          id: String,
          input: Anthropic::Beta::BetaBrowserMouseMoveInput,
          ?caller_: Anthropic::Models::Beta::beta_tool_use_caller,
          ?name: :mouse_move,
          ?toolset_name: :browser,
          ?type: :tool_use
        ) -> void

        def to_hash: -> {
          id: String,
          input: Anthropic::Beta::BetaBrowserMouseMoveInput,
          name: :mouse_move,
          toolset_name: :browser,
          type: :tool_use,
          caller_: Anthropic::Models::Beta::beta_tool_use_caller
        }
      end
    end
  end
end
