module Anthropic
  module Models
    module Beta
      type user_profile_create_params =
        {
          external_id: String?,
          metadata: ::Hash[Symbol, String],
          name: String?,
          relationship: Anthropic::Models::Beta::UserProfileCreateParams::relationship,
          betas: ::Array[Anthropic::Models::anthropic_beta]
        }
        & Anthropic::Internal::Type::request_parameters

      class UserProfileCreateParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor external_id: String?

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_accessor name: String?

        attr_reader relationship: Anthropic::Models::Beta::UserProfileCreateParams::relationship?

        def relationship=: (
          Anthropic::Models::Beta::UserProfileCreateParams::relationship
        ) -> Anthropic::Models::Beta::UserProfileCreateParams::relationship

        attr_reader betas: ::Array[Anthropic::Models::anthropic_beta]?

        def betas=: (
          ::Array[Anthropic::Models::anthropic_beta]
        ) -> ::Array[Anthropic::Models::anthropic_beta]

        def initialize: (
          ?external_id: String?,
          ?metadata: ::Hash[Symbol, String],
          ?name: String?,
          ?relationship: Anthropic::Models::Beta::UserProfileCreateParams::relationship,
          ?betas: ::Array[Anthropic::Models::anthropic_beta],
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          external_id: String?,
          metadata: ::Hash[Symbol, String],
          name: String?,
          relationship: Anthropic::Models::Beta::UserProfileCreateParams::relationship,
          betas: ::Array[Anthropic::Models::anthropic_beta],
          request_options: Anthropic::RequestOptions
        }

        type relationship = :external | :resold | :internal

        module Relationship
          extend Anthropic::Internal::Type::Enum

          EXTERNAL: :external
          RESOLD: :resold
          INTERNAL: :internal

          def self?.values: -> ::Array[Anthropic::Models::Beta::UserProfileCreateParams::relationship]
        end
      end
    end
  end
end
