module Anthropic
  module Resources
    class Beta
      class Organization
        class Analytics
          class Apps
            attr_reader chat: Anthropic::Resources::Beta::Organization::Analytics::Apps::Chat

            def initialize: (client: Anthropic::Client) -> void
          end
        end
      end
    end
  end
end
