module Anthropic
  module Resources
    class Beta
      class Organization
        class Analytics
          class Skills
            def list: (
              ?date: Date?,
              ?ending_date: Date?,
              ?filter: ::Array[String]?,
              ?group_by: ::Array[Anthropic::Models::Beta::Organization::Analytics::SkillListParams::group_by]?,
              ?limit: Integer?,
              ?order: Anthropic::Models::Beta::Organization::Analytics::SkillListParams::order?,
              ?order_by: String?,
              ?page: String?,
              ?starting_date: Date?,
              ?request_options: Anthropic::request_opts
            ) -> Anthropic::Internal::PageCursor[Anthropic::Beta::Organization::BetaAnalyticsSkillActivity]

            def initialize: (client: Anthropic::Client) -> void
          end
        end
      end
    end
  end
end
