module Anthropic
  module Resources
    class Completions
      def create:
        (
          Anthropic::Models::CompletionCreateParams | Hash[Symbol, top] params
        ) -> Anthropic::Models::Completion
        | (
          Anthropic::Models::CompletionCreateParams | Hash[Symbol, top] params,
          max_tokens_to_sample: Integer,
          model: Anthropic::Models::model,
          prompt: String,
          metadata: Anthropic::Models::Metadata,
          stop_sequences: Array[String],
          stream: Anthropic::Models::CompletionCreateParams::stream,
          temperature: Float,
          top_k: Integer,
          top_p: Float,
          request_options: Anthropic::request_opts
        ) -> Anthropic::Models::Completion

      def initialize: (client: Anthropic::Client) -> void
    end
  end
end
