module Anthropic
  module Resources
    class Models
      def retrieve: (
        String model_id,
        ?request_options: Anthropic::request_opts
      ) -> Anthropic::ModelInfo

      def list: (
        ?after_id: String,
        ?before_id: String,
        ?limit: Integer,
        ?request_options: Anthropic::request_opts
      ) -> Anthropic::Internal::Page[Anthropic::ModelInfo]

      def initialize: (client: Anthropic::Client) -> void
    end
  end
end
