module Anthropic
  module Resources
    class Models
      def retrieve:
        (
          String model_id,
          ?Anthropic::Models::ModelRetrieveParams | Hash[Symbol, top] params
        ) -> Anthropic::Models::ModelInfo
        | (
          String model_id,
          request_options: Anthropic::request_opts
        ) -> Anthropic::Models::ModelInfo

      def list:
        (
          ?Anthropic::Models::ModelListParams | Hash[Symbol, top] params
        ) -> Anthropic::Page[Anthropic::Models::ModelInfo]
        | (
          after_id: String,
          before_id: String,
          limit: Integer,
          request_options: Anthropic::request_opts
        ) -> Anthropic::Page[Anthropic::Models::ModelInfo]

      def initialize: (client: Anthropic::Client) -> void
    end
  end
end
