module Anthropic
  module Resources
    class Organization
      attr_reader api_keys: Anthropic::Resources::Organization::APIKeys

      attr_reader external_keys: Anthropic::Resources::Organization::ExternalKeys

      attr_reader federation: Anthropic::Resources::Organization::Federation

      attr_reader invites: Anthropic::Resources::Organization::Invites

      attr_reader service_accounts: Anthropic::Resources::Organization::ServiceAccounts

      attr_reader users: Anthropic::Resources::Organization::Users

      attr_reader workspaces: Anthropic::Resources::Organization::Workspaces

      attr_reader rate_limits: Anthropic::Resources::Organization::RateLimits

      attr_reader compliance_settings: Anthropic::Resources::Organization::ComplianceSettings

      def retrieve: (
        ?request_options: Anthropic::request_opts
      ) -> Anthropic::OrganizationInfo

      def initialize: (client: Anthropic::Client) -> void
    end
  end
end
