module Anthropic
  module Models
    module Organization
      type compliance_settings_state_disabled_param = { type: :disabled }

      class ComplianceSettingsStateDisabledParam < Anthropic::Internal::Type::BaseModel
        attr_accessor type: :disabled

        def initialize: (?type: :disabled) -> void

        def to_hash: -> { type: :disabled }
      end
    end
  end
end
