module Anthropic
  module Models
    module Organization
      type data_residency_update_config =
        {
          allowed_inference_geos: Anthropic::Models::Organization::DataResidencyUpdateConfig::allowed_inference_geos?,
          default_inference_geo: Anthropic::Models::Organization::DataResidencyUpdateConfig::default_inference_geo?
        }

      class DataResidencyUpdateConfig < Anthropic::Internal::Type::BaseModel
        attr_accessor allowed_inference_geos: Anthropic::Models::Organization::DataResidencyUpdateConfig::allowed_inference_geos?

        attr_accessor default_inference_geo: Anthropic::Models::Organization::DataResidencyUpdateConfig::default_inference_geo?

        def initialize: (
          ?allowed_inference_geos: Anthropic::Models::Organization::DataResidencyUpdateConfig::allowed_inference_geos?,
          ?default_inference_geo: Anthropic::Models::Organization::DataResidencyUpdateConfig::default_inference_geo?
        ) -> void

        def to_hash: -> {
          allowed_inference_geos: Anthropic::Models::Organization::DataResidencyUpdateConfig::allowed_inference_geos?,
          default_inference_geo: Anthropic::Models::Organization::DataResidencyUpdateConfig::default_inference_geo?
        }

        type allowed_inference_geos =
          :unrestricted
          | ::Array[Anthropic::Models::Organization::allowed_inference_geo]

        module AllowedInferenceGeos
          extend Anthropic::Internal::Type::Union

          def self?.variants: -> ::Array[Anthropic::Models::Organization::DataResidencyUpdateConfig::allowed_inference_geos]

          AllowedInferenceGeoArray: Anthropic::Internal::Type::Converter
        end

        type default_inference_geo = :global | :us

        module DefaultInferenceGeo
          extend Anthropic::Internal::Type::Enum

          GLOBAL: :global
          US: :us

          def self?.values: -> ::Array[Anthropic::Models::Organization::DataResidencyUpdateConfig::default_inference_geo]
        end
      end
    end
  end
end
