module Anthropic
  module Models
    class OrganizationUser = Organization::OrganizationUser

    module Organization
      type organization_user =
        {
          id: String,
          added_at: Time,
          email: String,
          name: String,
          role: Anthropic::Models::organization_role,
          type: :user
        }

      class OrganizationUser < Anthropic::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor added_at: Time

        attr_accessor email: String

        attr_accessor name: String

        attr_accessor role: Anthropic::Models::organization_role

        attr_accessor type: :user

        def initialize: (
          id: String,
          added_at: Time,
          email: String,
          name: String,
          role: Anthropic::Models::organization_role,
          ?type: :user
        ) -> void

        def to_hash: -> {
          id: String,
          added_at: Time,
          email: String,
          name: String,
          role: Anthropic::Models::organization_role,
          type: :user
        }
      end
    end
  end
end
