module Anthropic
  module Models
    module Organization
      type service_account_update_params =
        {
          service_account_id: String,
          description: String?,
          organization_role: Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role?
        }
        & Anthropic::Internal::Type::request_parameters

      class ServiceAccountUpdateParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor service_account_id: String

        attr_accessor description: String?

        attr_accessor organization_role: Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role?

        def initialize: (
          service_account_id: String,
          ?description: String?,
          ?organization_role: Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role?,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          service_account_id: String,
          description: String?,
          organization_role: Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role?,
          request_options: Anthropic::RequestOptions
        }

        type organization_role = :admin | :developer

        module OrganizationRole
          extend Anthropic::Internal::Type::Enum

          ADMIN: :admin
          DEVELOPER: :developer

          def self?.values: -> ::Array[Anthropic::Models::Organization::ServiceAccountUpdateParams::organization_role]
        end
      end
    end
  end
end
