module Anthropic
  module Models
    module Organization
      type service_account_archive_params =
        { service_account_id: String }
        & Anthropic::Internal::Type::request_parameters

      class ServiceAccountArchiveParams < Anthropic::Internal::Type::BaseModel
        extend Anthropic::Internal::Type::RequestParameters::Converter
        include Anthropic::Internal::Type::RequestParameters

        attr_accessor service_account_id: String

        def initialize: (
          service_account_id: String,
          ?request_options: Anthropic::request_opts
        ) -> void

        def to_hash: -> {
          service_account_id: String,
          request_options: Anthropic::RequestOptions
        }
      end
    end
  end
end
