module Anthropic
  module Models
    module Organization
      class WorkspaceRateLimitWorkspaceSource = Workspaces::WorkspaceRateLimitWorkspaceSource

      module Workspaces
        type workspace_rate_limit_workspace_source = { type: :workspace }

        class WorkspaceRateLimitWorkspaceSource < Anthropic::Internal::Type::BaseModel
          attr_accessor type: :workspace

          def initialize: (?type: :workspace) -> void

          def to_hash: -> { type: :workspace }
        end
      end
    end
  end
end
