module Anthropic
  module Resources
    class Organization
      class Workspaces
        class ServiceAccounts
          def retrieve: (
            String service_account_id,
            workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Organization::ServiceAccountWorkspaceMember

          def update: (
            String service_account_id,
            workspace_id: String,
            workspace_role: Anthropic::Models::Organization::no_billing_workspace_role,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Organization::ServiceAccountWorkspaceMember

          def list: (
            String workspace_id,
            ?limit: Integer,
            ?page: String?,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Internal::PageCursor[Anthropic::Organization::ServiceAccountWorkspaceMember]

          def add: (
            String workspace_id,
            service_account_id: String,
            workspace_role: Anthropic::Models::Organization::no_billing_workspace_role,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Organization::ServiceAccountWorkspaceMember

          def remove: (
            String service_account_id,
            workspace_id: String,
            ?request_options: Anthropic::request_opts
          ) -> Anthropic::Models::Organization::Workspaces::ServiceAccountRemoveResponse

          def initialize: (client: Anthropic::Client) -> void
        end
      end
    end
  end
end
