module Anthropic
  module Models
    module Beta
      module Organization
        module SpendLimits
          type beta_spend_limit_increase_request =
            {
              id: String,
              actor: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor,
              created_at: Time,
              period: Anthropic::Models::Beta::Organization::beta_spend_limit_period,
              resolved_at: Time?,
              resolved_by: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by?,
              spend_summary: Anthropic::Beta::Organization::BetaSpendSummary?,
              status: Anthropic::Models::Beta::Organization::SpendLimits::beta_spend_limit_increase_request_status,
              type: :spend_limit_increase_request
            }

          class BetaSpendLimitIncreaseRequest < Anthropic::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor actor: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor

            attr_accessor created_at: Time

            attr_accessor period: Anthropic::Models::Beta::Organization::beta_spend_limit_period

            attr_accessor resolved_at: Time?

            attr_accessor resolved_by: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by?

            attr_accessor spend_summary: Anthropic::Beta::Organization::BetaSpendSummary?

            attr_accessor status: Anthropic::Models::Beta::Organization::SpendLimits::beta_spend_limit_increase_request_status

            attr_accessor type: :spend_limit_increase_request

            def initialize: (
              id: String,
              actor: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor,
              created_at: Time,
              period: Anthropic::Models::Beta::Organization::beta_spend_limit_period,
              resolved_at: Time?,
              resolved_by: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by?,
              spend_summary: Anthropic::Beta::Organization::BetaSpendSummary?,
              status: Anthropic::Models::Beta::Organization::SpendLimits::beta_spend_limit_increase_request_status,
              ?type: :spend_limit_increase_request
            ) -> void

            def to_hash: -> {
              id: String,
              actor: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor,
              created_at: Time,
              period: Anthropic::Models::Beta::Organization::beta_spend_limit_period,
              resolved_at: Time?,
              resolved_by: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by?,
              spend_summary: Anthropic::Beta::Organization::BetaSpendSummary?,
              status: Anthropic::Models::Beta::Organization::SpendLimits::beta_spend_limit_increase_request_status,
              type: :spend_limit_increase_request
            }

            type actor =
              Anthropic::Beta::Organization::BetaSpendLimitUserActor
              | Anthropic::Beta::Organization::BetaSpendLimitScopedAPIKeyActor

            module Actor
              extend Anthropic::Internal::Type::Union

              type type_ = :user_actor | :scoped_api_key_actor

              module Type
                extend Anthropic::Internal::Type::Enum

                USER_ACTOR: :user_actor
                SCOPED_API_KEY_ACTOR: :scoped_api_key_actor

                def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::Actor::type_]
              end

              def self?.variants: -> ::Array[Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor]

              def self.new:
                (
                  type: :user_actor | "user_actor",
                  deleted: bool,
                  email_address: String?,
                  name: String?,
                  user_id: String
                ) -> Anthropic::Beta::Organization::BetaSpendLimitUserActor
                | (
                  type: :scoped_api_key_actor | "scoped_api_key_actor",
                  scoped_api_key_id: String
                ) -> Anthropic::Beta::Organization::BetaSpendLimitScopedAPIKeyActor
                | (
                  type: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::Actor::type_
                  | String,
                  ?deleted: bool,
                  ?email_address: String?,
                  ?name: String?,
                  ?user_id: String,
                  ?scoped_api_key_id: String
                ) -> Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::actor
            end

            type resolved_by =
              Anthropic::Beta::Organization::BetaSpendLimitUserActor
              | Anthropic::Beta::Organization::BetaSpendLimitScopedAPIKeyActor

            module ResolvedBy
              extend Anthropic::Internal::Type::Union

              type type_ = :user_actor | :scoped_api_key_actor

              module Type
                extend Anthropic::Internal::Type::Enum

                USER_ACTOR: :user_actor
                SCOPED_API_KEY_ACTOR: :scoped_api_key_actor

                def self?.values: -> ::Array[Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::ResolvedBy::type_]
              end

              def self?.variants: -> ::Array[Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by]

              def self.new:
                (
                  type: :user_actor | "user_actor",
                  deleted: bool,
                  email_address: String?,
                  name: String?,
                  user_id: String
                ) -> Anthropic::Beta::Organization::BetaSpendLimitUserActor
                | (
                  type: :scoped_api_key_actor | "scoped_api_key_actor",
                  scoped_api_key_id: String
                ) -> Anthropic::Beta::Organization::BetaSpendLimitScopedAPIKeyActor
                | (
                  type: Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::ResolvedBy::type_
                  | String,
                  ?deleted: bool,
                  ?email_address: String?,
                  ?name: String?,
                  ?user_id: String,
                  ?scoped_api_key_id: String
                ) -> Anthropic::Models::Beta::Organization::SpendLimits::BetaSpendLimitIncreaseRequest::resolved_by
            end
          end
        end
      end
    end
  end
end
